### ISSUE TITLE
手动换源/把弹幕渲染到别的视频网站上

### ISSUE THREAD

**Issue by swgr424** [bilibili-helper/bilibili-helper-o#108]
这是一个feature request。如果想实现的话，应该会是一个大坑 XD

就，出于各种你懂的以及你不懂的原因，B站老视频常常有这种情况：在B站上已经看不了了（源失效/官方屏蔽等等），但第三方网站（比如优酷）其实还能看，并且原始的弹幕数据在B站上也都还能拿到。这种情况下，是否有可能结合第三方的视频以及B站的弹幕，让用户能看到有弹幕版的视频？

案例：
http://www.bilibili.com/video/av1155461/index_4.html
http://v.youku.com/v_show/id_XNzE4Njg1MDMy.html

一个想法是可不可能提供一种手动的换源操作（不知道播放器本身对那些外站的支持如何），又或者能够把弹幕直接渲染到外站的视频播放页面里（工作量大概需要写一个简化的弹幕渲染引擎）。

**Comment by zacyu** [comment]
嗯, 我也考虑过这个可能性. 可以用 HTML5 实现, 但是主要问题还是在于视频播放时间的同步.

**Comment by swgr424** [comment]
感觉大部分视频的弹幕并不需要非常精确（毫秒级）的同步。这样的话，哪怕是让观众手动调整弹幕的同步offset，似乎也可以接受的样子。
