### ISSUE TITLE
希望可以支持chromecast

### ISSUE THREAD

**Issue by imshuhao** [bilibili-helper/bilibili-helper-o#52]
好想用电视看啊

**Comment by siuond** [comment]
大赞如果能加入类似nicocast的功能支持chromecast

**Comment by tangblack** [comment]
用這個 Android APP 能把 bilibili 投射至 chromecast

[Android APP 下載](https://play.google.com/store/apps/details?id=com.geraldwallace.bpashen)

操作畫面
https://youtu.be/_OySVnbZGv8
