### ISSUE TITLE
画中画开关无效

### ISSUE THREAD

**Issue by sll523911** [bilibili-helper/bilibili-helper-o#641]
### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):WIN10
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):任何浏览器
3. 扩展版本:1.2.9

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
![image](https://user-images.githubusercontent.com/45690827/70430771-76ef8480-1ab6-11ea-923a-b5dbaa356927.png)
![image](https://user-images.githubusercontent.com/45690827/70430785-81118300-1ab6-11ea-9451-14329200952a.png)

**Comment by jjj201200** [comment]
遵命，收到（🙋‍♂️
