### ISSUE TITLE
与另一个拓展 pakku 同时使用，视频弹幕查询及下载 功能用不了

### ISSUE THREAD

**Issue by qmzmdqs** [bilibili-helper/bilibili-helper-o#646]
### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): windows 10
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): 79.0.3945.79（正式版本） （64 位）
3. 扩展版本: version 1.2.13（正式版）

### 重现步骤/尝试的解决方案
使用另一个拓展 [pakku](https://github.com/xmcp/pakku.js) ，导致 视频弹幕查询及下载 功能用不了

> ps: 刚开始，是可以共存的，最近一两个月吧 视频弹幕查询及下载 ，我也不知道是不是修改配置的问题，还是哪一次更新的问题。

**Comment by qmzmdqs** [comment]
先反馈在这里了，后面如果需要，我再在另一个拓展那边反馈 =_=

**Comment by jjj201200** [comment]
之前做了主动兼容，既然是同时开启的，你可以暂时关闭助手的这个功能，我之后会处理这个问题

**Comment by qmzmdqs** [comment]
这个问题是修复了吗，今天突然看到，可以点击一个按钮才加载完整弹幕，可以正常显示了

**Comment by jjj201200** [comment]
修复了吧

**Comment by qmzmdqs** [comment]
感觉作者
