### ISSUE TITLE
为什么下载不了视频

### ISSUE THREAD

**Issue by CloudyEagle** [bilibili-helper/bilibili-helper-o#655]
环境信息
请填写以下信息:

操作系统 (Windows/macOS/Linux):Win 10
浏览器版本:任何chromium支持插件的浏览器
扩展版本: 1.2.14.2
重现步骤/尝试的解决方案
功能已开启，但菜单里没有要下载的视频，那个小点点了也没用。
![TIM截图20200116212630](https://user-images.githubusercontent.com/58777085/72529112-8d53e180-38a7-11ea-8031-5da298b97f4a.png)
![TIM截图20200116213110](https://user-images.githubusercontent.com/58777085/72529120-90e76880-38a7-11ea-85b5-f51d93e79397.png)

**Comment by jjj201200** [comment]
请给一下出现问题的视频地址，然后尝试来回切换一下清晰度

**Comment by CloudyEagle** [comment]
看的是这个视频，av83700911，切换过清晰度。但大多数的视频好像都下载不了

**Comment by CloudyEagle** [comment]
是B站把下载给屏蔽了吗？那我手机缓存还是可以的，还是换接口了？

**Comment by jjj201200** [comment]
应该只是做了一些逻辑上的改动，你反复来回切换清晰度的话还是可以获取到的

**Comment by CloudyEagle** [comment]
我试过了，还是没有用。不过外挂字幕下载还是能用的
![TIM截图20200117215223](https://user-images.githubusercontent.com/58777085/72618213-94e1bc00-3975-11ea-81d6-a0e9ce9efc1a.png)

视频av83868705

**Comment by CloudyEagle** [comment]
额，好像是720p及以下是可以的，1080p与1080p+用不了。
![TIM截图20200117221319](https://user-images.githubusercontent.com/58777085/72618920-256ccc00-3977-11ea-9621-db5d9b2b94be.png)
![TIM截图20200117221400](https://user-images.githubusercontent.com/58777085/72618942-2e5d9d80-3977-11ea-830c-7956b1121cfa.png)
![TIM截图20200117221435](https://user-images.githubusercontent.com/58777085/72618954-33bae800-3977-11ea-94ae-ce467ee7ebf0.png)

**Comment by CloudyEagle** [comment]
好吧，确实是能用，就是操作有点繁琐，要不停地切换。如果能不需要反复切换就好了。

**Comment by jjj201200** [comment]
我会修一下的

**Comment by jjj201200** [comment]
请不要关闭哈，该问题还没有修复至线上版本
