### ISSUE TITLE
稍后再看界面插件失效

### ISSUE THREAD

**Issue by ljcbaby** [bilibili-helper/bilibili-helper-o#659]
稍后再看页面插件失效
夜间模式，助手按钮均无

**Comment by jjj201200** [comment]
感谢反馈，但请您先按照模板填写一下基本信息

**Comment by ljcbaby** [comment]
请填写以下信息:

操作系统 (Windows/macOS/Linux): Windows8.1 企业版
浏览器版本(您可以在 [菜单/帮助/关于] 下查看): Microsoft Edge 版本 79.0.309.71 (官方内部版本) (64 位)
扩展版本: 1.2.15 来自谷歌商店
重现步骤/尝试的解决方案：

在稍后再看的视频页面（https://www.bilibili.com/watchlater/#/avid/pid），插件不起效，包括深色模式和悬浮的助手图标均无

**Comment by jjj201200** [comment]
扩展版本已经更新到1.2.21了
