### ISSUE TITLE
专栏图片保存功能导致样式错乱

### ISSUE THREAD

**Issue by kimufly** [bilibili-helper/bilibili-helper-o#686]
# 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): Windows 10 1909 
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): Microsoft Edge chromium 80.0.361.69
3. 扩展版本: BILIBILI HELPER version 1.2.16

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)

> 重现页面链接
https://www.bilibili.com/read/cv5272819

> 功能截图
![image](https://user-images.githubusercontent.com/7436694/77604921-95d33300-6f4e-11ea-9b40-69568a52e105.png)

> 样式错乱截图
![image](https://user-images.githubusercontent.com/7436694/77604990-c0bd8700-6f4e-11ea-85b4-f5c489ef8710.png)

**Comment by unbadfish** [comment]
请问一下怎么用图片保存功能呀；]

**Comment by jjj201200** [comment]
1.2.18版本已经在商店发布，请及时更新

**Comment by jjj201200** [comment]
@unbadfish 鼠标放在图片上会出现下载图片按钮，部分点击没有反应的无法下载
