### ISSUE TITLE
“锁屏提醒值”会在 Chromium 浏览器中“传染”给其它带有角标的扩展

### ISSUE THREAD

**Issue by duoduoffff** [bilibili-helper/bilibili-helper-o#687]
## 问题反馈
在您提交问题前, 请检查以下项目:
- [x] 您在**报告一个 bug** 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [x] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): Windows 10 build 19587.1000
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): Microsoft Edge (Chromium) 版本 82.0.453.2 (官方内部版本) dev (64 位)
3. 扩展版本: 1.2.16 正式版

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)

![image](https://user-images.githubusercontent.com/46983115/77637084-09496480-6f90-11ea-93f1-14fd1f66592e.png)

不知道你们浏览器有没有遇到过这种情况，就是这个“锁屏提醒值”会传染给其它带有角标的扩展的？

1. 随便安装一个会显示角标的其它扩展在 Chromium 上。
2. 鼠标移上去，不管是什么扩展，只要显示了角标，都会有“锁屏提醒值”。

只要一个扩展带有角标，就会带上这个“锁屏提醒值”。没有角标的不受影响。

该问题在 Firefox（developer 75.0 b8）上不会出现。

还有就是锁屏提醒值到底是干什么用的啊？

**Comment by jjj201200** [comment]
完全不了解，从来没见过这个词汇，一脸懵逼。

**Comment by xmcp** [comment]
应该就是Edge团队的迷惑本地化而已。
![image](https://user-images.githubusercontent.com/6646473/77650320-4a4c7380-6fa6-11ea-9931-b1ca78c8c2c3.png)
这个词没什么问题，就是角标数值的意思。

**Comment by duoduoffff** [comment]
哦对，刚刚把 Edge 调成英语试了一下，确实是 Edge 特有的，应该是为了方便屏幕阅读器读出来而设计的

**Comment by bamboo3650** [comment]
终于有人跟我一样发现这个问题，目前不知道如何解决，因为它到一定的时间真的会锁屏了！

**Comment by xmcp** [comment]
跟锁屏没关系的，就是badge value的意思，MS的又一处迷惑翻译而已。坐和放宽就行了。

**Comment by bamboo3650** [comment]
可是我电脑设置1小时才锁屏的。但是只要这个浏览器大开着就大概几分钟后就会锁屏，所以不知道哪里出了问题！
