### ISSUE TITLE
Edge商店的所谓哔哩哔哩助手是经过修改的恶意软件

### ISSUE THREAD

**Issue by xmcp** [bilibili-helper/bilibili-helper-o#695]
Edge商店有一个[提供方显示为edge ext的插件](https://microsoftedge.microsoft.com/addons/detail/pdhnlcdephcdoaofoljhccphajdjngmd)，该插件相比于Chrome Web Store的哔哩哔哩助手有几处不同。详细分析如下：

<details>
<summary>点击展开</summary>

1. 增加了【访问所有网站】和【访问浏览记录】的权限
![image](https://user-images.githubusercontent.com/6646473/79042783-2e470400-7c2d-11ea-852e-baddf0ba58b7.png)

2. 增加了多种统计代码
![image](https://user-images.githubusercontent.com/6646473/79043369-5cc6de00-7c31-11ea-9d91-3f0ec1afce46.png)

3. 增加了恶意脚本 `pic.js`、`content.js`、`statics/imgs/logo.png`
![image](https://user-images.githubusercontent.com/6646473/79043083-7cf59d80-7c2f-11ea-8137-9f51a5f81020.png)

经过解密，`statics/imgs/logo.png` 中的代码有多种恶意功能，例如为购物网站增加返利链接等。解密后的代码详见 [PasteBin](https://paste.ubuntu.com/p/WMzkqg4ZHK/)。
![image](https://user-images.githubusercontent.com/6646473/79043338-2c7f3f80-7c31-11ea-8eba-f98b2f45420a.png)

`content.js` 和 `pic.js` 的部分代码抄自 “猫爪” Chrome 扩展，用于掩人耳目。
![image](https://user-images.githubusercontent.com/6646473/79043606-b8459b80-7c32-11ea-8d5a-354056dcfc69.png)

在掩人耳目的代码之后，增加了一些具有远程控制功能的代码。
![image](https://user-images.githubusercontent.com/6646473/79043758-dc55ac80-7c33-11ea-8815-8b79726c6119.png)

暂时没有找到这些恶意功能何时被调用。可能会在后续更新后激活。

4. 删除了部分代码（这正是设置页面白屏的原因）
![image](https://user-images.githubusercontent.com/6646473/79043871-9c42f980-7c34-11ea-88a0-14e19f096d7e.png)

![image](https://user-images.githubusercontent.com/6646473/79043899-baa8f500-7c34-11ea-86d5-252a44de3523.png)

不清楚为什么要删除这些东西。
</details>

总之，Edge 商店中的该扩展应该是一起有组织的恶意软件攻击行为，可能导致浏览器历史泄露，以及被用来赚取返利佣金。
**建议所有安装了Edge商店版本恶意扩展的用户立即卸载，开发者可以联系Edge商店进行维权。**

（pakku也经历过被恶意修改后上传360扩展市场的类似情况，当时是邮件联系客服解决的，供参考。）

**Comment by jjj201200** [comment]
惊呆，感谢感谢，我立刻发邮件过去

**Comment by jjj201200** [comment]
讲真要是他没改崩被用户反馈我还远不知道竟然上架4天了，这个世界好可怕

**Comment by PanXinYi** [comment]
如果不是xmcp发现这是恶意扩展，我还认为商店那个拓展是作者审核通过的版本，空欢喜一场:(

**Comment by r0tare1eccA** [comment]
感谢大佬指路，已经卸载

**Comment by QiaoXiaobing** [comment]
感谢，已下载，坐等大佬上传

**Comment by QiaoXiaobing** [comment]
感谢，已卸载，坐等大佬上传

**Comment by jjj201200** [comment]
Edge已经正式上架
https://microsoftedge.microsoft.com/addons/detail/fcfebhekhbkhjjimonjmbgmkbclheaoh?hl=zh-CN

**Comment by jjj201200** [comment]
![image](https://user-images.githubusercontent.com/3397549/79630702-17049b00-8186-11ea-9e24-22c9995c96fd.png)

**Comment by xmcp** [comment]
@jjj201200
这是怎么发的邮件啊……建议直接按安全问题（而不是用户体验问题）报上去，问题描述稍微强硬一点，说 “它侵犯了我的版权” “它有恶意代码，违反了贵司的规定” “希望立刻下架，停止滥用行为” 之类的，效果可能会比较好？（我之前跟360浏览器的客服沟通就用的这种思路）
比如 “My browser extension has been counterfeited on Edge Addons Store（附上真实和假冒扩展的URL）. The fake extension deletes some of the UI element like the donation link and contains malware code. I report this abuse to Edge Store and hopefully it will be removed.”

https://support.microsoft.com/en-us/supportforbusiness/productselection ↓
![image](https://user-images.githubusercontent.com/6646473/79631061-fbe75a80-8188-11ea-8abf-ccdca69abe6f.png)

**Comment by jjj201200** [comment]
@xmcp 就是这么写的，我再发一遍强硬的看看。简直无语了。

**Comment by jjj201200** [comment]
@xmcp 我已经通过人工服务向上提交处理申请了，商业支持太贵啦233

**Comment by celeron533** [comment]
> 你发的这个是商业支持要付费的

但作为版权方可以用版权申诉的吧

**Comment by jjj201200** [comment]
@celeron533 经过讨论我们认为这里姑且是没有版权纠纷的，因为本身MIT协议对版权没有限制，但是我们已经按照最严肃的安全问题来反馈，这点绝对是没有异议的。虽然如此，即便我已经通过3种不同的途径来反馈问题，但微软方便并没有任何处理。

**Comment by memoryz** [comment]
我已通过内部渠道向微软安全部门报告此插件，安全部门已经直接通知相关的团队。

**Comment by celeron533** [comment]
[off-topic] SwitchyOmega在edge商店中的那个也是加过料的
感觉edge商店里假冒扩展很多

**Comment by xmcp** [comment]
就是那个叫“edge ext”的开发者，他传的基本都是这种套壳的扩展

**Comment by memoryz** [comment]
两个插件我都反馈给了相关团队。

**Comment by memoryz** [comment]
"Proxy SwitchyOmega"插件应该已经下架了。
