### ISSUE TITLE
关于本项目修改开源协议和未来的改动

### ISSUE THREAD

**Issue by jjj201200** [bilibili-helper/bilibili-helper-o#697]
由于最近发生在Edge商城中恶意篡改并假冒助手上架的问题。
我和咕咕讨论决定从2.x版本开始将该项目从 [MIT许可证](https://zh.wikipedia.org/wiki/MIT%E8%A8%B1%E5%8F%AF%E8%AD%89) 改为 [Mozilla公共许可证](https://zh.wikipedia.org/wiki/Mozilla%E5%85%AC%E5%85%B1%E8%AE%B8%E5%8F%AF%E8%AF%81) 

作为一款已经开源数年且在不断维护的软件，我们希望可以在保证开放的同时避免不必要的麻烦，保证用户的使用和隐私安全。

这次在Edge的申诉中，我们发现MIT协议并不符合我们的预期，它太过宽松，没办法明确我们不允许图谋不轨之人滥用开源代码的立场，所以我们暂且先决定了上述的事宜。

此外，从2.x开始我们还会发布两个版本，一个版本如同现在一样，另一个则为不开源。
因为从2.x开始助手中将加入一些需要服务器支持的功能（例如：设置同步，多账号跨设备登录，消息通知等高级功能）。开源版本中将不包含这些功能相关模块和代码。我们希望尽可能保护那些用户数据敏感的关键代码，尽可能减小来自图谋不轨之人的威胁。

介于助手当前的工程结构的特性，我们会将其分为「bilibili-helper」和「bilibili-helper-o」，有些像chrome和chromium的关系。而bilibili-helper-o则会是上面提到的Mozilla公共许可证下的。

由于上面的区分，我们之前的「严格筛选需要添加的功能」的立场在开源版本中将会发生改变。当然我们仍旧会保证该版本不会失控，但是如无例外，只会出现一些修复性的改动，非开源版本将仍旧保持「尽可能只增加绝大多数用户需要的功能」这个宗旨，成为我们主要开发的部分。

**因此这里欢迎并希望大家能够构建出一个你们自己想要的助手**

以上。

**Comment by DarthMikuH** [comment]
请问什么时候才能下载BV号的视频

**Comment by jjj201200** [comment]
@DarthMikuH 更新到1.2.16版本以上
