### ISSUE TITLE
4K视频下载支持

### ISSUE THREAD

**Issue by sino1641** [bilibili-helper/bilibili-helper-o#700]
请保留一种您需要的语言版本的报告模板
please leave only one kind of these template

## 问题反馈
在您提交问题前, 请检查以下项目:
- [x] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [x] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):WKindows
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):Chrome 81
3. 扩展版本:1.2.16

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)
希望增加4K视频下载，4K视频下目前仅可点选1080P+或1080@60。

Much thx:)

**Comment by fuchanghao** [comment]
同样的问题，实测无论是firefox 12.16还是edge的1.2.17.3都有同样的问题，测试视频：https://www.bilibili.com/video/av412909688

**Comment by jjj201200** [comment]
我看了一下，现在quality=120即画质4K时接口只能返回最高112即1080P+的画质，当4K时没有flv源，只有dash数据，只能下载到影视频分离的两个通道源。不知道有没有什么别的方案

**Comment by fuchanghao** [comment]
> 
> 
> @fuchanghao @sino1641 我看了一下，现在的方案下请求quality=120即画质4K时接口只能返回最高112即1080P+的画质，当4K时没有flv源，只有dash数据，只能下载到音视频分离的两个通道源。不知道有没有什么别的方案
> 
> 如果能够接受分别下载音视频源的话，倒是可以提供这个下载途径，只是感觉绝大多数用户应该不需要

目前使用官方安卓的客户端是可以支持4K视频下载的，那个是利用什么的原理呢，不过音视频下载后合并不行吗？

**Comment by jjj201200** [comment]
@fuchanghao 浏览器上没办法合并视频，因为需要合并算法需要消耗大量内存。极小的视频倒是可以，但是这和我们讨论的4K就无关了

**Comment by sino1641** [comment]
> @fuchanghao 浏览器上没办法合并视频，因为合并算法需要消耗大量内存。极小的视频倒是可以，但是这和我们讨论的4K就无关了
> 
> 这也是为什么助手目前的合并下载经常出问题的原因

@jjj201200 能否做到分别下载mp4和aac，然后由用户使用本地软件（例如ffmpeg或格式工厂等）进行合并，再在界面上辅以适当的文字提示。
~~其实能了解到贵扩展的用户应该也会有基本的计算机知识（幸存者偏差（？））~~

**Comment by unbadfish** [comment]
> 
> 
> > @fuchanghao 浏览器上没办法合并视频，因为合并算法需要消耗大量内存。极小的视频倒是可以，但是这和我们讨论的4K就无关了
> > 这也是为什么助手目前的合并下载经常出问题的原因
> 
> @jjj201200 能否做到分别下载mp4和aac，然后由用户使用本地软件（例如ffmpeg或格式工厂等）进行合并，再在界面上辅以适当的文字提示。
> ~其实能了解到贵扩展的用户应该也会有基本的计算机知识（幸存者偏差（？））~

可以发布一个.bat文件，拖入就合并
（要出教学视频，教用户配置ffmpeg，有常识的人应该能弄好）
@jjj201200

**Comment by jjj201200** [comment]
@unbadfish 这些就交给你们了

**Comment by unbadfish** [comment]
请问您是调侃还是说真心话？
我只是说出来供参考，请您不要引战。
若我技术水平够高，我早就pull request了，我提issue说明我有这种想法，但是技术不够，请您谅解



---原始邮件---
发件人: "DrowsyFlesh"<notifications@github.com&gt;
发送时间: 2020年4月25日(周六) 晚上10:59
收件人: "bilibili-helper/bilibili-helper-o"<bilibili-helper-o@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"unbadfish"<3066893506@qq.com&gt;;
主题: Re: [bilibili-helper/bilibili-helper-o] [feature Request]4K视频下载支持 (#700)




 
@unbadfish 这些就交给你们了

**Comment by jjj201200** [comment]
@fuchanghao 咦。。。不好意思不知道为什么你会突然感到被冒犯到。并没有不好的用词呀。
不过正如我说的比如bat文件或者教程，目前都不会去做，用户需要自己去解决。
毕竟谈不上义务，或许之后我有闲心了会突然想帮他家直接解决这个问题，那可能也是另外的的话题了。

**Comment by unbadfish** [comment]
可能是b站风纪委员当久了吧……对不起【鞠躬】
那我们就把这个话题了结了吧，还是讨论代码的问题，不要在这些问题上纠结。谢谢。



---原始邮件---
发件人: "DrowsyFlesh"<notifications@github.com&gt;
发送时间: 2020年4月25日(周六) 晚上11:13
收件人: "bilibili-helper/bilibili-helper-o"<bilibili-helper-o@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"unbadfish"<3066893506@qq.com&gt;;
主题: Re: [bilibili-helper/bilibili-helper-o] [feature Request]4K视频下载支持 (#700)




 
@fuchanghao 咦。。。不好意思不知道为什么你会突然感到被冒犯到。并没有不好的用词呀。
 不过正如我说的比如bat文件或者教程，目前都不会去做，用户需要自己去解决。
 毕竟谈不上义务，或许之后我有闲心了会突然想帮他家直接解决这个问题，那可能也是另外的的话题了。

**Comment by fuchanghao** [comment]
> 
> 
> @fuchanghao 浏览器上没办法合并视频，因为合并算法需要消耗大量内存。极小的视频倒是可以，但是这和我们讨论的4K就无关了
> 
> 这也是为什么助手目前的合并下载经常出问题的原因

是否可以参考Video DownloadHelper，安装一个类似合作应用的东西实现下载后自动合并。
安装可以直接choco install vdhcoapp

Source: https://github.com/mi-g/vdhcoapp

**Comment by jjj201200** [comment]
@fuchanghao 感谢，我会去看看可行性如何

**Comment by sino1641** [comment]
[Local YouTube Downloader](https://greasyfork.org/en/scripts/369400-local-youtube-downloader)
可以参考这类脚本，也是将音视频合并，体验上可以接受其合并过程CPU开销

**Comment by jjj201200** [comment]
@sino1641 就是如上所提到的我们也尝试过，小视频没问题，容量过大的视频不行，现在那么多高清晰度视频需要

**Comment by jjj201200** [comment]
目前推荐使用IDM分别下载音视频然后通过ffmpeg合并
例如：`ffmpeg.exe -i %audio% -i %video% -acodec copy -vcodec copy %video%.mp4`

**Comment by 1265578519** [comment]
这样不现实啊，别搞这些bat什么的。。能直接解析吗，我内存大，有1TB内存，64位浏览器单进程上限高，不存在崩溃的可能性

**Comment by jjj201200** [comment]
@1265578519 大哥你当真1T内存？惊吓
然，我暂时搞不定

**Comment by 1265578519** [comment]
![1](https://user-images.githubusercontent.com/6442439/83409218-97d1da80-a446-11ea-89a5-9d836971737e.jpeg)
![photo_2020-04-15_21-36-05](https://user-images.githubusercontent.com/6442439/83409230-9b656180-a446-11ea-8334-7a2a9847ff12.jpg)

**Comment by jjj201200** [comment]
@1265578519 可以的，不过不行233

**Comment by Daniel2022** [comment]
@jjj201200 作者还没找到解析4K视频的方法吗？如果没有我提供一个：这是从浏览器解析出的插件的请求https://api.bilibili.com/x/player/playurl?cid=<cid>&avid=<av号>&qn=120&otype=json&requestFrom=bilibili-helper，最高只能获得1080p+或1080p60，其实只缺一个请求参数fourk=1，加上就有4K的flv视频链接了。希望能帮到你。

**Comment by jjj201200** [comment]
@Daniel2022 你好，该方法获取不到4K视频源

**Comment by jjj201200** [comment]
@Daniel2022 感谢感谢，最近并没有推进这个issue，所以一直到现在都没有进展，实在惭愧。
这个参数确实在官方接口中出现了，之后会将其实现并在更新日志中特别鸣谢。

最后再次感谢你的帮助~

**Comment by 1265578519** [comment]
https://api.bilibili.com${apiPath}?avid=${aid}&cid=${cid}&otype=json&fourk=1&qn=${qn}

**Comment by jjj201200** [comment]
1.2.24已发布，请及时更新
