### ISSUE TITLE
快速访问能增加稍后再看吗

### ISSUE THREAD

**Issue by darknesshub** [bilibili-helper/bilibili-helper-o#701]
### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): Win 10 1909
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):chrome 80
3. 扩展版本:1.2.16正式版

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)

![Snipaste_2020-04-27_10-02-43](https://user-images.githubusercontent.com/41509944/80327380-80fbff00-886e-11ea-9811-906be68fbee0.jpg)
如果可以的话希望在此增加稍后再看的功能，很多时候刷到好看的视频都是直接添加到稍后再看，谢谢。

**Comment by jjj201200** [comment]
可

**Comment by jjj201200** [comment]
与 #688 重复
