### ISSUE TITLE
自动领取其他直播间的上舰奖励

### ISSUE THREAD

**Issue by wuyuanpoi** [bilibili-helper/bilibili-helper-o#702]
能否开发一个【自动领取其他直播间的上舰奖励】的功能

**Comment by jjj201200** [comment]
这个要考虑一下，还不能给你们明确的答复

**Comment by jjj201200** [comment]
刚看了一下，自动领取其他直播间上的奖励这就和自动抽奖差不多了，所以不会进行开发。具体原因就和当初下架自动抽奖功能一样。具体请看本项目github中的相关wiki
