### ISSUE TITLE
个人空间背景变白

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [bilibili-helper/bilibili-helper-o#703]
### 环境信息
请填写以下信息:
> 操作系统: Windows 10 1909
> 浏览器版本: Google Chrome 81.0.4044.129
> 扩展版本: 1.2.16.5 测试版

### 重现步骤/尝试的解决方案

> 出现问题的页面地址
> https://space.bilibili.com/

**启用插件后个人空间背景上半部分一大块变成了白色的，复现率100%**

![QQ截图20200430101818](https://user-images.githubusercontent.com/45261195/80674405-5b782b00-8ae4-11ea-9828-f0952ce320c5.jpg)

**Comment by jjj201200** [comment]
1.2.18版本已经在商店发布，请及时更新
