### ISSUE TITLE
edge浏览器中总是会关闭弹幕

### ISSUE THREAD

**Issue by shazhuyang666666** [bilibili-helper/bilibili-helper-o#704]
问题反馈

即使我已经关闭“默认关闭弹幕显示”，它依然会自动关闭弹幕显示，且重新关闭、重装扩展都无效。

环境信息
操作系统:Windows 10 Professional for Workstation x86,版本1909
浏览器版本:Microsoft Edge 81.0.416.68 (官方内部版本) (32 位)
扩展版本:1.17.3

重现步骤/尝试的解决方案
每次加载视频页面时都会将弹幕关闭，包括刷新和重新打开标签页，随机打开一个有效视频页可复现

**Comment by shazhuyang666666** [comment]
经查，与其他扩展不兼容导致，现已解决。

**Comment by jjj201200** [comment]
@shazhuyang666666 能否告知是什么扩展？我好看看能不能竟可能做好兼容

**Comment by shazhuyang666666** [comment]
其实我也不知道……我把所有扩展都卸了……
