### ISSUE TITLE
视频弹幕查询及下载功能在有大量高级弹幕时导致浏览器长时间假死

### ISSUE THREAD

**Issue by Qixingchen** [bilibili-helper/bilibili-helper-o#706]
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):   
windows
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):  
 Chrome 版本 81.0.4044.138（正式版本） （64 位）
3. 扩展版本:  
BILIBILI HELPER
version 1.2.16（正式版）

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)

示例视频 https://www.bilibili.com/video/BV1Pt4y1y7K7  
有 300 余条高级弹幕, 在开启 视频弹幕查询及下载 功能后,在页面加载时(即使不点击助手图标)就会导致页面有约20秒的卡死.  
经 performance 查询确认到是助手的一条正则导致的卡顿

 

![image](https://user-images.githubusercontent.com/4182240/82731928-9fa1c880-9d3c-11ea-860b-1cc5c0667c24.png)

**Comment by xmcp** [comment]
特殊弹幕的判断其实不需要用正则，B站自己都没用，直接一个try-catch：
![image](https://user-images.githubusercontent.com/6646473/82732794-0970a100-9d42-11ea-9631-87a866ab2134.png)

**Comment by jjj201200** [comment]
@xmcp thx~他们似乎已经加大了灰测力度，是时候发布了

**Comment by jjj201200** [comment]
@Qixingchen 已经在群里发了测试版~

**Comment by jjj201200** [comment]
1.2.18版本已经在商店发布，请及时更新
