### ISSUE TITLE
无法查询弹幕

### ISSUE THREAD

**Issue by CloudyEagle** [bilibili-helper/bilibili-helper-o#707]
1. 操作系统: Windows 10
2. 浏览器版本: Chromium内核版，如Edge、Google Chrome、360浏览器等
3. 扩展版本:1.2.16.5(beta release)

在我看哔哩哔哩看电影时，想看看发弹幕的人是谁时，发现一个弹幕记录都没有。
换普通的番剧和Upload-er的视频，也还是一样查询不到弹幕；刷新页面后也没用，接着换浏览器也还是一样的结果，不知道时什么原因，望解决。
![TIM截图20200524210605](https://user-images.githubusercontent.com/58777085/82754889-93803e80-9e02-11ea-893f-00fa6a7e25a2.png)
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
悄悄问一下，可不可以为没有绑定手机的用户提供领取登录硬币和领取直播间银瓜子的功能。
我有个小号是这样的。
之前一个大号解绑手机后再次注册，再绑定邮箱后解绑手机，前一个账号的手机号再绑回来。

**Comment by jjj201200** [comment]
1.2.18已经在商店发布，请及时更新
回答你的问题：很抱歉~不可以~b站是不会允许这种操作的，而且也做不到
