### ISSUE TITLE
开启扩展时番剧/稍后再看/专栏页面背景色样式出错

### ISSUE THREAD

**Issue by moqiaoduo** [bilibili-helper/bilibili-helper-o#708]
## 问题反馈
在您提交问题前, 请检查以下项目:
- [x] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [x] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] 您已填写了系统环境信息.

开启扩展时以下页面背景色样式出错：
- 番剧
- 稍后再看
- 专栏

### 环境信息
请填写以下信息:
1. 操作系统: Windows
2. 浏览器版本: 83.0.4103.61
3. 扩展版本: 1.2.18

### 重现步骤/尝试的解决方案
关闭扩展时，样式正常：
![normal](https://user-images.githubusercontent.com/20296531/82855194-36d56e80-9f3d-11ea-8010-252344d128a7.png)

开启扩展时，背景色变灰：
![crash](https://user-images.githubusercontent.com/20296531/82855218-4359c700-9f3d-11ea-8718-edaa0b6bf20b.png)

清除缓存刷新，仍然无效

**Comment by qmzmdqs** [comment]
原来这是 bug ，不是 feature ，我还在设置里找开关没找到。。

**Comment by moqiaoduo** [comment]
> 原来这是 bug ，不是 feature ，我还在设置里找开关没找到。。

你是怎么认为它是feature的哈哈哈哈哈哈

**Comment by qmzmdqs** [comment]
因为我是在搜索页发现的，灰白护眼嘛

**Comment by Howard20181** [comment]
+1 
在阅读文章时发现了这一问题

**Comment by dogseedcat** [comment]
+1

**Comment by jjj201200** [comment]
群里已经有测试版了哈，然后我一会儿去商店发布，估计最晚一天后会上架，最快可能只要几小时

**Comment by jjj201200** [comment]
1.2.19版本已经上线，该版本还有中弹幕查询栏弹幕加载不完整的问题，后续版本会修复
