### ISSUE TITLE
【功能请求】视频默认循环播放

### ISSUE THREAD

**Issue by Cai-Zurun** [bilibili-helper/bilibili-helper-o#710]
请保留一种您需要的语言版本的报告模板
please leave only one kind of these template

## 问题反馈
在您提交问题前, 请检查以下项目:
- [ ] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [ ] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [ ] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [ ] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):
3. 扩展版本:

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)

## Feedback
Before submitting your issue, please check to make sure of the following:
- [ ] You are reporting a bug or making a feature request. If you are looking for general support, please contact us directly or comment at our project homepage.
- [ ] Your issue is not a duplicate of an existing issue. If there is an open issue of the same topic, please just comment under it.
- [ ] If you are reporting a bug, please make sure it can be reproduced in the latest release or master branch. Also, please specify detailed procedures to reproduce the bug (screenshots would be greatly appreciated).
- [ ] You have filled out your system environment info.

### Environment Info
Please fill out the following:
1. Operating System (Windows/macOS/Linux):
2. Chrome Version (You can check this under [Menu/Help/About]):
3. Extension Version:

You can see this on extension options page. You can also put the latest commit ID here if you are reporting about the master branch. 

### Steps to Reproduce / Attempted solution
Please be specific here, thanks :)

**Comment by xmcp** [comment]
![image](https://user-images.githubusercontent.com/6646473/83349573-76022600-a368-11ea-908c-789f5aa4d20c.png)
你说这个？

**Comment by Cai-Zurun** [comment]
> ![图片](https://user-images.githubusercontent.com/6646473/83349573-76022600-a368-11ea-908c-789f5aa4d20c.png)
> 你说这个？

是的，可不可以实现一打开视频就默认循环？

**Comment by jjj201200** [comment]
@Cai-Zurun 请详细描述一下新功能请求的相关细节，功能的具体描述，使用场景，有无特殊情况，以便于我们判断是否添加到助手中

就现在来看，我没有看懂为何需要这个功能，难道你每个打开的视频都要自动开启循环？当需要循环的时候手动开启一下不就行了？

**Comment by Cai-Zurun** [comment]
> @Cai-Zurun 请详细描述一下新功能请求的相关细节，功能的具体描述，使用场景，有无特殊情况，以便于我们判断是否添加到助手中
> 
> 就现在来看，我没有看懂为何需要这个功能，难道你每个打开的视频都要自动开启循环？当需要循环的时候手动开启一下不就行了？
需求背景：喜欢一边看钢琴区的b站视频一边学习，而每次都要手动开启循环就比较麻烦。所以希望来个自动打开循环。不知道这是不是属于个人情况。

**Comment by jjj201200** [comment]
@Cai-Zurun 
![image](https://user-images.githubusercontent.com/3397549/83371207-5adcf800-a3f4-11ea-9842-fe2044af1a6a.png)
b站的待看列表有列表循环功能哦，你可以这么去操作一下。目前还没有充分里有添加这个功能，希望你能理解

**Comment by Cai-Zurun** [comment]
好的。理解，理解。弱弱的问一句，可不可以用油猴+JS脚本实现这一功能？

**Comment by jjj201200** [comment]
@Cai-Zurun 油猴就是js脚本，完全可以实现
