### ISSUE TITLE
  自动领取瓜子失效

### ISSUE THREAD

**Issue by ddaodan** [bilibili-helper/bilibili-helper-o#712]
### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):Windows 10
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):70.0.3538.25
3. 扩展版本:1.2.19

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
![image](https://user-images.githubusercontent.com/40017293/83727311-7146b600-a677-11ea-9791-de1d49b95644.png)

**Comment by jjj201200** [comment]
访问被拒表示你的号被暂时封禁，请注意是否使用脚本或者插件过度。

**Comment by ddaodan** [comment]
> 访问被拒表示你的号被暂时封禁，请注意是否使用脚本或者插件过度。

去问了下客服，可能是之前有国外IP登陆的记录导致的，不是插件的Bug就行
