### ISSUE TITLE
能不能搞个B站锁定CDN的方法，防止播放卡顿

### ISSUE THREAD

**Issue by 1265578519** [bilibili-helper/bilibili-helper-o#713]
播放卡顿？
“替换upos视频服务器”选项
在设置中有个“替换upos视频服务器”选项，针对大陆的视频有效果，可以试下。

改hosts
港澳台的视频解析出来的视频文件的域名是upos-hz-mirrorakam.akamaized.net，这家CDN貌似没有国内的节点，大多数情况下这个域名都会指向美国的IP，速度特别慢。他们是有香港/台湾节点的，速度会快很多。手动改hosts，将域名解析到较快的IP，能够缓解卡顿的问题。

https://greasyfork.org/zh-CN/scripts/25718-%E8%A7%A3%E9%99%A4b%E7%AB%99%E5%8C%BA%E5%9F%9F%E9%99%90%E5%88%B6

比如这种的

比如官方测速工具，，七牛CDN就是最垃圾的，贼卡，老是一秒一缓冲
![1](https://user-images.githubusercontent.com/6442439/83792919-56ebf700-a6ce-11ea-908a-8ee18ddd1b5f.png)
![2](https://user-images.githubusercontent.com/6442439/83792927-5ce1d800-a6ce-11ea-80f3-e8c51a2ba9a9.png)

官方测速工具
https://www.bilibili.com/blackboard/video-diagnostics.html

BVID：BV1J54y1Q7Da
CID：197668243

**Comment by qmzmdqs** [comment]
原来是这个原因吗，b站总是隔一段时间就来一次大姨夫，播放一卡一卡的，明明播其他视频网站好好的，而且有一段时间，每次开头第几秒的时候总会卡一下。。

**Comment by jjj201200** [comment]
这个油猴脚本已经好长时间了
我理解你的需求是希望助手可以实现自动测速后自动代理到较快的地址是吗？还是说有别的意思

**Comment by 1265578519** [comment]
@jjj201200 这个脚本好像偷密码，我感觉不太靠谱，希望助手搞一个
https://github.com/ipcjs/bilibili-helper/issues/631

**Comment by ipcjs** [comment]
> @jjj201200 这个脚本好像偷密码，我感觉不太靠谱，希望助手搞一个
> [ipcjs/bilibili-helper#631](https://github.com/ipcjs/bilibili-helper/issues/631)

神TM偷密码，帐号授权的过程中你哪步输了密码？

**Comment by jjj201200** [comment]
@ipcjs 兄弟你去处理他提交的issue呗，在原issue中谈论这个话题好吗，和这里无关。
然后，我这里暂时也没有精力加这个请求的功能。

**Comment by zz5678** [comment]
的确是可以锁定的，这几个国内 cdn 的 域名在B站的播放链接里可以互相对调，参考这里 https://github.com/iawia002/annie/issues/640#issuecomment-601204518

而且，即使是同一个 域下的不同 cdn 解析 IP 下载/播放 速度都有巨大差距，b 站的技术好烂的，cdn 分配相当乱，分到了质量差的 IP 会卡死

**Comment by 1265578519** [comment]
@zz5678 就是不知道插件能不能实现设置一个CDN的值，肯定是可以相互使用的啊，不然我也不会发帖子出来问了

**Comment by zz5678** [comment]
> @zz5678 就是不知道插件能不能实现设置一个CDN的值，肯定是可以相互使用的啊，不然我也不会发帖子出来问了

竟然两边帖子都是你，呵呵，我回复了。 https://github.com/bilibili-helper/bilibili-helper-o/issues/661#issuecomment-669249048

**Comment by zz5678** [comment]
实际上，防止 b 站卡顿，还有一个绝杀办法，b 站国内这些非 dash api 给出的 cdn 都做了**带宽速度限制**，所以加上网络问题，以及 cdn 分配的技术错误，就会卡顿，反而海外 `upos-hz-mirrorakam.akamaized.net` 的多数 cdn 都没有限速，但需要自己找到合适的海外 IP。

**Comment by BugKun** [comment]
看到这个还没关闭的Issue，我想起了自己之前做的解决方案，感兴趣的话可以试一下  
[akam-proxy](https://github.com/BugKun/akam-proxy)

**Comment by hlc1209** [comment]
这个页面搜索权重很高，所以借地方贴一个最简单最快速的解决方案

https://github.com/Kanda-Akihito-Kun/ccb

安装脚本后，切换源到香港地区，或者大陆地区，就能彻底解决海外卡顿问题
注意！很多大陆cdn在海外是无法直连的，需要不断切换测试，直到找到一个能连接的，效果就会很好。所以目前还是首选香港CDN，但有些小众视频香港cdn需要回源，这时候大陆cdn效果会更好。
