### ISSUE TITLE
无法下载ass/xml的弹幕文件

### ISSUE THREAD

**Issue by DarthMikuH** [bilibili-helper/bilibili-helper-o#714]
<img width="1280" alt="截屏2020-06-08 下午7 23 28" src="https://user-images.githubusercontent.com/62818311/84025074-898f3b80-a9bd-11ea-8378-3600f29ea4be.png">

Mac
Chrome 83.0.4103.97
version 1.2.16（正式版）

**Comment by DarthMikuH** [comment]
由于网络较慢选择了360p，已登陆B站账号

**Comment by qiyulan** [comment]
当前版本 1.2.19  
1.2.18 和 1.2.19 都修正了弹幕相关的功能,建议升级到19看看还有没有问题

**Comment by JasonKhew96** [comment]
发 issue 前请确认是不是最新版

**Comment by DarthMikuH** [comment]
有17版了吗



---原始邮件---
发件人: "Jason_Khew"<notifications@github.com&gt;
发送时间: 2020年6月9日(周二) 下午2:38
收件人: "bilibili-helper/bilibili-helper-o"<bilibili-helper-o@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"DarthMikuH"<darthmiku@foxmail.com&gt;;
主题: Re: [bilibili-helper/bilibili-helper-o] 无法下载ass/xml的弹幕文件 (#714)




 
发 issue 前请确认是不是最新版

**Comment by DarthMikuH** [comment]
谢谢



---原始邮件---
发件人: "祈星辰"<notifications@github.com&gt;
发送时间: 2020年6月8日(周一) 晚上10:59
收件人: "bilibili-helper/bilibili-helper-o"<bilibili-helper-o@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"DarthMikuH"<darthmiku@foxmail.com&gt;;
主题: Re: [bilibili-helper/bilibili-helper-o] 无法下载ass/xml的弹幕文件 (#714)




 
当前版本 1.2.19
 1.2.18 和 1.2.19 都修正了弹幕相关的功能,建议升级到19看看还有没有问题
