### ISSUE TITLE
使用扩展导致CPU占用率过高

### ISSUE THREAD

**Issue by Maple-pro** [bilibili-helper/bilibili-helper-o#715]
### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): Windows10
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): Google Chrome Version 85.0.4164.2
3. 扩展版本: 1.2.19

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)
1. 使用bilibili-help扩展
2. 打开bilibili.com
3. 打开一个视频播放
4. 打开任务管理器，发现CPU占用率很高，达98%左右；关闭扩展后，同样条件下，CPU占用率仅30%左右
![image](https://user-images.githubusercontent.com/52351480/84028906-1d640600-a9c4-11ea-9bc0-ff9e5d45d17a.png)
![image](https://user-images.githubusercontent.com/52351480/84028958-35d42080-a9c4-11ea-91c9-df6609ab5992.png)

**Comment by jjj201200** [comment]
感谢反馈，请发一个测出问题时的视频地址~

**Comment by Maple-pro** [comment]
https://www.bilibili.com/video/BV1Pv41167FE
这是测试时的视频，但在我这里不管哪个视频都会出现这种问题。
（我会把地址更新到issue上）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"DrowsyFlesh"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月9日(星期二) 晚上8:16
收件人:&nbsp;"bilibili-helper/bilibili-helper-o"<bilibili-helper-o@noreply.github.com&gt;;
抄送:&nbsp;"乘风"<1719957182@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bilibili-helper/bilibili-helper-o] 使用扩展导致CPU占用率过高 (#715)





 
感谢反馈，请发一个测出问题时的视频地址~

**Comment by jjj201200** [comment]
@Maple-pro 恩，我是在确认并排除变量因素，请问有安装其他扩展并尝试禁用，以便于排除其他因素吗
由于最近暂时还没有同样的反馈，所以希望可以定位一下问题所在。

**Comment by Maple-pro** [comment]
我刚才查了一下，应该和我装的Tampermonkey有关（以下简称tm）。bilibili help简称bh打开tm（无脚本），打开bh，CPU占用率达90%多；
打开tm（无脚本），关闭bh，CPU占用率30%左右；
关闭tm，打开bh，30%左右；
关闭tm，关闭bh，30%左右。
tm版本：4.10&nbsp; &nbsp;黑色的那个版本




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "DrowsyFlesh"<notifications@github.com&gt;; 
发送时间: 2020年6月9日(星期二) 晚上8:23
收件人: "bilibili-helper/bilibili-helper-o"<bilibili-helper-o@noreply.github.com&gt;; 
抄送: "乘风"<1719957182@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [bilibili-helper/bilibili-helper-o] 使用扩展导致CPU占用率过高 (#715)





 
@Maple-pro 恩，我是在确认并排除变量因素，请问有安装其他扩展并尝试禁用，以便于排除其他因素吗
 由于最近暂时还没有同样的反馈，所以希望可以定位一下问题所在。

**Comment by jjj201200** [comment]
@Maple-pro 那可能要逐一排查是哪个油猴脚本和助手会导致这个问题了

**Comment by Maple-pro** [comment]
我在测试的时候没有任何脚本，把所有脚本都关掉了



---原始邮件---
发件人: "DrowsyFlesh"<notifications@github.com&gt;
发送时间: 2020年6月9日(周二) 晚上8:45
收件人: "bilibili-helper/bilibili-helper-o"<bilibili-helper-o@noreply.github.com&gt;;
抄送: "Maples"<1719957182@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [bilibili-helper/bilibili-helper-o] 使用扩展导致CPU占用率过高 (#715)




 
@Maple-pro 那可能要逐一排查是哪个油猴脚本和助手会导致这个问题了

**Comment by jjj201200** [comment]
@Maple-pro 啊不好意思，漏看了，我去下一个看看能不能复现你的问题

**Comment by jjj201200** [comment]
@Maple-pro 我觉得尝试重新安装一下油猴？但是按理说油猴也不会导致这个问题才对，没有加载脚本的话，两者应该没什么关系。
或许可以确认一下油猴的安装来源是有安全问题。或者你可以看一下浏览器的任务管理器，哪一个进程导致的问题

**Comment by Maple-pro** [comment]
我重新安装了油猴，里面没有添加任何脚本，再测试。




未播放视频时：


禁用油猴后（仍然使用bh），恢复30%

重新安装的油猴还是4.10，从chrome应用商店安装。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "DrowsyFlesh"<notifications@github.com&gt;; 
发送时间: 2020年6月9日(星期二) 晚上8:51
收件人: "bilibili-helper/bilibili-helper-o"<bilibili-helper-o@noreply.github.com&gt;; 
抄送: "乘风"<1719957182@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [bilibili-helper/bilibili-helper-o] 使用扩展导致CPU占用率过高 (#715)





 
@Maple-pro 我觉得尝试重新安装一下油猴？但是按理说油猴也不会导致这个问题才对，没有加载脚本的话，两者应该没什么关系。
 或许可以确认一下油猴的安装来源是有安全问题。或者你可以看一下浏览器的任务管理器，哪一个进程导致的问题

**Comment by Maple-pro** [comment]
我重新安装了油猴，里面没有添加任何脚本，再测试。
![image](https://user-images.githubusercontent.com/52351480/84152006-b1060700-aa96-11ea-9a58-4c15164f13e1.png)
![image](https://user-images.githubusercontent.com/52351480/84152021-b5cabb00-aa96-11ea-8bd6-aa8a54201ad9.png)

未播放视频时：
![image](https://user-images.githubusercontent.com/52351480/84152040-bb280580-aa96-11ea-815f-11247b93a3a5.png)

禁用油猴后（仍然使用bh），恢复30%

重新安装的油猴还是4.10，从chrome应用商店安装。

**Comment by jjj201200** [comment]
![image](https://user-images.githubusercontent.com/3397549/84220394-45a74e00-ab05-11ea-8284-e8d1b469dd39.png)
先关闭所有其他扩展看看，现在测试结果让人迷惑不解

**Comment by Maple-pro** [comment]
不知道为什么，现在这个问题消失了😂，明明我什么都没动

**Comment by jjj201200** [comment]
@Maple-pro 好吧，大概是由于一些我们都未曾想到的原因吧，如果之后又出现了可以重开这个issue

**Comment by Maple-pro** [comment]
好的，打扰了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "DrowsyFlesh"<notifications@github.com&gt;; 
发送时间: 2020年6月13日(星期六) 晚上8:05
收件人: "bilibili-helper/bilibili-helper-o"<bilibili-helper-o@noreply.github.com&gt;; 
抄送: "乘风"<1719957182@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [bilibili-helper/bilibili-helper-o] 使用扩展导致CPU占用率过高 (#715)





 
@Maple-pro 好吧，大概是由于一些我们都未曾想到的原因吧，如果之后又出现了可以重开这个issue
