### ISSUE TITLE
直播间网页崩溃

### ISSUE THREAD

**Issue by Kagero8Yukikaze** [bilibili-helper/bilibili-helper-o#720]
开着插件看直播一段时间后网页会崩溃，显示STATUS_ACCESS_VIOLATION
并且我用最新的edge和chrome都是这样，关闭插件后就没有崩溃过了

**Comment by Kagero8Yukikaze** [comment]
chrome版本83.0.4103.106
edge版本83.0.478.54

**Comment by jjj201200** [comment]
助手版本号多少，下载来源是哪儿

**Comment by Kagero8Yukikaze** [comment]
> 助手版本号多少，下载来源是哪儿

版本号1.2.19，谷歌商店下的。今天开插件看直播的时候没有出现崩溃.....不知道是为什么

**Comment by jjj201200** [comment]
@Kagero8Yukikaze 可以先尝试用排除法，关闭其他扩展并且重启浏览器，看问题是否仍然存在

**Comment by Kagero8Yukikaze** [comment]
> @Kagero8Yukikaze 可以先尝试用排除法，关闭其他扩展并且重启浏览器，看问题是否仍然存在

终于弄明白了，应该是一个油猴插件的锅，谢谢dalao！

**Comment by jjj201200** [comment]
@Kagero8Yukikaze 可否告知是哪个脚本，以便于我们以后排查

**Comment by Kagero8Yukikaze** [comment]
> @Kagero8Yukikaze 可否告知是哪个脚本，以便于我们以后排查

https://github.com/qxinGitHub/Remove-web-limits-
