### ISSUE TITLE
1.2.20 下载弹幕不全

### ISSUE THREAD

**Issue by microka** [bilibili-helper/bilibili-helper-o#721]
1. 操作系统 (Windows/macOS/Linux): Windows 10 1909 (18363.900)
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): 83.0.4103.106 stable 64bit
3. 扩展版本: 1.2.20（正式版）

https://www.bilibili.com/video/BV1uE411t7Mw

![微信截图_20200621133245](https://user-images.githubusercontent.com/490351/85217491-576dd880-b3c4-11ea-9139-8b771bea4f9b.png)
这个视频B站页面以及助手都查询到目前有1218条弹幕

![微信截图_20200621133340](https://user-images.githubusercontent.com/490351/85217533-a4ea4580-b3c4-11ea-80ed-59c49a05fe3b.png)
但通过助手下载的ass格式弹幕发现里面只有100多条弹幕

![微信截图_20200621133506](https://user-images.githubusercontent.com/490351/85217537-ad428080-b3c4-11ea-8d37-40320418be3f.png)
而通过助手下载的xml格式弹幕，可以看到弹幕内容是全的。

而通过 https://greasyfork.org/scripts/31259-bilibilidanmaku 获取的 xml 弹幕转为 ass 格式则没有这个问题。

附两个 xml 弹幕文件：
[xml.zip](https://github.com/bilibili-helper/bilibili-helper-o/files/4808965/xml.zip)

**Comment by jjj201200** [comment]
1.2.21版本已经更新，其中修复了该问题，及时更新哦~
