### ISSUE TITLE
哔哩哔哩助手在edge浏览器不显示动态通知

### ISSUE THREAD

**Issue by CorkFyv** [bilibili-helper/bilibili-helper-o#733]

**Comment by jjj201200** [comment]
请按照模板填写比较信息，谢谢~

**Comment by SplitGemini** [comment]
## 问题反馈
在您提交问题前, 请检查以下项目:
- [x] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [x] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):
Windows 10 Pro 2004
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):
Chrome 84.0.4147.125（正式版本） （64 位）
3. 扩展版本:
1.2.21

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)
已登录bilibili，但是只显示直播消息，不显示动态消息
![image](https://user-images.githubusercontent.com/34861918/90848580-ce612680-e39f-11ea-99a5-b5946d2933e9.png)

**Comment by jjj201200** [comment]
@SplitGemini 请尝试卸载后重新安装
