### ISSUE TITLE
今天直播间更新后，屏蔽进间信息失效了

### ISSUE THREAD

**Issue by 1265578519** [bilibili-helper/bilibili-helper-o#738]
今天直播间更新后，屏蔽进间信息失效了
![image](https://user-images.githubusercontent.com/6442439/88984174-7d5d9580-d2ff-11ea-8727-03b21c527805.png)
![image](https://user-images.githubusercontent.com/6442439/88984184-82bae000-d2ff-11ea-882c-a94cc3da7020.png)

**Comment by 1265578519** [comment]
搞错了，，我还以为这个是助手的功能

**Comment by jjj201200** [comment]
这就是助手功能，进场信息
