### ISSUE TITLE
无法检查更新/获取更新信息失败，并且无法进入官网

### ISSUE THREAD

**Issue by RSNGK** [bilibili-helper/bilibili-helper-o#739]
如题，无法进行更新检查，并且无法进入官网（在尝试自行寻找解决方案）
![image](https://user-images.githubusercontent.com/54470504/89015893-6a23e780-d34a-11ea-95e8-bdf6eaada773.png)

**Comment by jjj201200** [comment]
使用控制变量法进行排查，先关闭所有代理软件和扩展程序，然后打开助手尝试复现问题

**Comment by RSNGK** [comment]
好吧过了一段时间自动好了...这就很迷...
我怀疑我电脑/网络抽风
