### ISSUE TITLE
能否增加一个设置选项，让推送的视频地址能让用户自行选择是BV还是AV号

### ISSUE THREAD

**Issue by SekiBetu** [bilibili-helper/bilibili-helper-o#742]
## 问题反馈
在您提交问题前, 请检查以下项目:
- [√] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [√] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [√] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [√] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): WIN10 19041.388
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): Google Chrome 84.0.4147.105
3. 扩展版本: 1.2.21（正式版）

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
点击推送的视频后
![image](https://user-images.githubusercontent.com/38283893/89101096-9c862100-d3ec-11ea-95b1-74daadee8b3a.png)
![image](https://user-images.githubusercontent.com/38283893/89101104-a3ad2f00-d3ec-11ea-815d-ef899380d69a.png)
跳转的地址都是AV号的，AV号在逐渐被抛弃的大趋势下，是否考虑默认是BV号，用户手动在设置里开启转换再转换成AV号跳转？

**Comment by jjj201200** [comment]
之后会改成BV号，不会考虑提供av号转换。

**Comment by jjj201200** [comment]
在1.2.24中做出了改动，请及时更新
