### ISSUE TITLE
特定文章的内容会被错误移除

### ISSUE THREAD

**Issue by AnnAngela** [bilibili-helper/bilibili-helper-o#743]
## 问题反馈
在您提交问题前, 请检查以下项目:
- [x] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [x] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): Windows 10 2004 (OS 19041.388)
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): Microsoft Edge Dev 86.0.587.0
3. 扩展版本: 1.2.21

### 重现步骤/尝试的解决方案
启用扩展后访问 https://www.bilibili.com/read/cv6993789 就会发现文章的内容会被错误地删除。
原因可能是该文章的部分内容是以 `TextNode` 形式直接放在 `.article-holder` 里而不是用 `<p/>` 包裹的。

**Comment by NebulaL** [comment]
1. 操作系统 Windows 10 2004 (OS 18363.959)
2. 浏览器版本Mircosoft Edge Beta 85.0.564.18 
3. 扩展版本: 1.2.21
有同样的问题
