### ISSUE TITLE
B站的直播已经删除了瓜子宝箱，插件也可以删除自动领宝箱的功能了

### ISSUE THREAD

**Issue by lvzhenbo** [bilibili-helper/bilibili-helper-o#755]
请保留一种您需要的语言版本的报告模板
please leave only one kind of these template

## 问题反馈
在您提交问题前, 请检查以下项目:
- [x] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [x] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):Windows10
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):85
3. 扩展版本:1.2.21

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)
如题

**Comment by jjj201200** [comment]
了解，暂时不用管他哈

**Comment by CloudyEagle** [comment]
> 了解，暂时不用管他哈

但直播功能板块里的自动签到能否不要删除；
虽然不能手动签到，但可以用您的插件强行签到；
领取部分奖励，拜托了！

**Comment by jjj201200** [comment]
现在不能手动签到了吗。。我好像有看到呀
