### ISSUE TITLE
弹幕下载不全

### ISSUE THREAD

**Issue by xihuaziyi** [bilibili-helper/bilibili-helper-o#759]
1. 操作系统 (Windows10):
2. 浏览器版本(chrome):
3. 扩展版本:1.2.21

下载电影的弹幕不完整，比如《绿皮书》，只能下载前36分钟的弹幕，不知道是不是个例

**Comment by jjj201200** [comment]
可以提供一下视频播放页面的地址吗

**Comment by jjj201200** [comment]
[bilibilihelper_1.2.22-beta.9.crx.zip](https://github.com/bilibili-helper/bilibili-helper-o/files/5222446/bilibilihelper_1.2.22-beta.9.crx.zip)
你用这个版本试试看，是还没有发布的测试版本，我测下来没有什么问题了，同时今天将会发布该版本至商店

**Comment by xihuaziyi** [comment]
https://www.bilibili.com/bangumi/play/ep326711
上面是地址
发送自 Windows 10 版邮件应用

发件人: DrowsyFlesh
发送时间: 2020年9月15日 12:08
收件人: bilibili-helper/bilibili-helper-o
抄送: xihuaziyi; Author
主题: Re: [bilibili-helper/bilibili-helper-o] 弹幕下载不全 (#759)

可以提供一下视频播放页面的地址吗

**Comment by xihuaziyi** [comment]
这个可以用，能下载完整弹幕了
请问什么时候出4K下载啊？

发送自 Windows 10 版邮件应用

发件人: DrowsyFlesh
发送时间: 2020年9月15日 12:23
收件人: bilibili-helper/bilibili-helper-o
抄送: xihuaziyi; Author
主题: Re: [bilibili-helper/bilibili-helper-o] 弹幕下载不全 (#759)

bilibilihelper_1.2.22-beta.9.crx.zip
你用这个版本试试看，是还没有发布的测试版本，我测下来没有什么问题了，同时今天将会发布该版本至商店

**Comment by jjj201200** [comment]
我刚才发的这个版本已经可以下载4K了，但是取消了版权视频下载

**Comment by jjj201200** [comment]
在1.2.24中修复，请及时更新
