### ISSUE TITLE
能否请您帮我(也是帮大家)解决这个播放器的问题

### ISSUE THREAD

**Issue by Z-fly** [bilibili-helper/bilibili-helper-o#763]
[https://www.bilibili.com/video/BV1et411b7Ky](https://www.bilibili.com/video/BV1et411b7Ky)
这个视频的分P直接从第3秒开始播放。
Flash播放器是没有问题的。
这个能否通过助手解决？B站客服问了，他们没法解决。

我用蓝牙耳机看视频会有延迟导致音画不同步，能否加个手动调整音频播放延迟的功能？（这个可以在未来助手版本里实现）

**Comment by Cotch22** [comment]
Flash播放器和HTML播放器的源是不一样的，这个视频很显然是B站二压的时候出了问题，只能由创作者重新上传解决；

如果要改音轨延迟就会涉及到hook播放器，目前不考虑，嘻嘻。
而且蓝牙耳机目前都有音视频自适应延迟，这不是播放器需要考虑的。
