### ISSUE TITLE
播放页黑夜模式-UP用户名字体颜色

### ISSUE THREAD

**Issue by ansonhorse** [bilibili-helper/bilibili-helper-o#766]
### 环境信息
请填写以下信息:
1. 操作系统: macOS
2. 浏览器版本: 85.0.4183.121 (Official Build) (64-bit)
3. 扩展版本: 1.2.21（stable release）

### 重现步骤/尝试的解决方案
1. 打开 https://www.bilibili.com/video/BV1iD4y1o7po 或其他B站视频。
2. 开启`夜间模式`
3. 查看页面右上角UP信息
![image](https://user-images.githubusercontent.com/7548142/94103494-6bafee80-fe67-11ea-96d1-dfff15829dff.png)

鼠标悬浮时样式正常：
![image](https://user-images.githubusercontent.com/7548142/94103565-8e420780-fe67-11ea-9b97-f6f8ddaa87b1.png)

**Comment by jjj201200** [comment]
感谢反馈，正在审核中的1.2.22版本已经 修复该问题，记得留意一下
