### ISSUE TITLE
测试版安装方法失效了 现在可以用的方法是:

### ISSUE THREAD

**Issue by AgoniXX** [bilibili-helper/bilibili-helper-o#768]
测试版按照方法失效了 现在可以用的方法是:
1、首先把需要安装的第三方插件，后缀.crx 改成 .rar，然后解压，得到一个文件夹
2、再打开chrome://extensions/谷歌扩展应用管理，点击右上角的开发者模式，就可以看到“加载正在开发的扩展程序”这一选项。
3、选择刚才步骤1中解压好的文件夹，确定
4、确认新增扩展程序，点击添加，成功添加应用程序。

**Comment by jjj201200** [comment]
感谢提醒，已经补充修改扩展名步骤
