### ISSUE TITLE
测试版的自动全屏 看完视频后 点相关推荐 跳转的视频 不能自动全屏

### ISSUE THREAD

**Issue by AgoniXX** [bilibili-helper/bilibili-helper-o#770]
测试版的自动全屏 看完视频后 点相关推荐 跳转的视频 不能自动全屏

**Comment by Cotch22** [comment]
自动全屏的机制是在打开视频页面的时候注入，点推荐视频的跳转是在当前页发生的，B站播放器会重写全屏状态，我们目前没有持续注入的功能，以后会做哒

**Comment by jjj201200** [comment]
请更新到测试群里的1.2.23-beta.4
