### ISSUE TITLE
能不能把代码迁移到 码云 github 翻墙都不稳定 暗黑模式用户名看不见

### ISSUE THREAD

**Issue by gcfkhy** [bilibili-helper/bilibili-helper-o#771]
能不能把代码迁移到 码云 github 翻墙都不稳定

**Comment by jjj201200** [comment]
确实这段时间由于一些原因github终于又被不同程度的搞了
不过暂时不迁移，github终究是最主流的代码仓库服务商
如果选举过后github仍旧处于被持续禁止访问的状态，我会把官网的服务器挪到国内，但是仓库暂时不会考虑其他选项

内按摩师用户名不可见的问题已经在最新测试版中修复，请及时更新，注意安装方法不同于正式版本

**Comment by gcfkhy** [comment]
> 确实这段时间由于一些原因github终于又被不同程度的搞了
> 不过暂时不迁移，github终究是最主流的代码仓库服务商
> 如果选举过后github仍旧处于被持续禁止访问的状态，我会把官网的服务器挪到国内，但是仓库暂时不会考虑其他选项
> 
> 内按摩师用户名不可见的问题已经在最新测试版中修复，请及时更新，注意安装方法不同于正式版本

我下载了测试版发现正确. 本来想改的 结果发现 是react的 一下子都尴尬了 ￣□￣｜｜

**Comment by jjj201200** [comment]
react并不难学
