### ISSUE TITLE
夜间模式下up主名字的颜色有时会变成和背景色一样，导致看不到字

### ISSUE THREAD

**Issue by shishirong** [bilibili-helper/bilibili-helper-o#772]
## 问题反馈
![image](https://user-images.githubusercontent.com/16620315/95659091-528a8b80-0b51-11eb-97cf-f4500a4085cc.png)

### 环境信息
1. 操作系统 (Windows/macOS/Linux):Windows10
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):Microsoft Edge
3. 扩展版本:version 1.2.21（正式版）

### 重现步骤/尝试的解决方案
当播放完一个视频之后点击相关推荐的时候会出现

**Comment by jjj201200** [comment]
感谢反馈，之后的版本会修复这个问题

**Comment by jjj201200** [comment]
在1.2.24中修复，请及时更新
