### ISSUE TITLE
深色模式样式错误 收到的赞 - 点赞详情 页面

### ISSUE THREAD

**Issue by CloudyEagle** [bilibili-helper/bilibili-helper-o#776]
1. 操作系统 : Maybe All Systems
2. 浏览器版本 : Maybe All Browsers
3. 扩展版本 :1.2.24
重现步骤：
深色/夜间模式下，[收到的赞]里具体内容默认怎么会这样，只有鼠标飘过后才会变色出现。
![QQ截图20201017003841](https://user-images.githubusercontent.com/58777085/96286979-caeec200-1013-11eb-8ee6-d367b40c556e.jpg)
![QQ截图20201017003850](https://user-images.githubusercontent.com/58777085/96286989-d0e4a300-1013-11eb-8845-418c53b957c5.jpg)

**Comment by jjj201200** [comment]
能够提供一下链接

**Comment by Cotch22** [comment]
已修复，如有需要可以拉取dev分支自行编译
https://github.com/bilibili-helper/bilibili-helper-o/commit/9839fe8426fe47bb6041b28295867250e3769831
