### ISSUE TITLE
添加主页分区屏蔽功能

### ISSUE THREAD

**Issue by memorydream** [bilibili-helper/bilibili-helper-o#777]
RT

B站主页分区太多，有部分不感兴趣的分区，希望在主页与主页右侧的list-box上屏蔽这些分区

**Comment by jjj201200** [comment]
恭喜恭喜，获得本项目第一个777

**Comment by memorydream** [comment]
> 恭喜恭喜，获得本项目第一个777

哇，倍感荣幸，受宠若惊(x

**Comment by memorydream** [comment]
> 恭喜恭喜，获得本项目第一个777

我在写这个模块时遇到了一些问题：
当kind为global时，模块被分配在other配置下，该模块有subPage，当我尝试开关subPage中的checkbox时，引发了一个Error；
我尝试把该模块的kind分配为video，checkbox正常开关，但是无法在主页上加载；
在调试工具里断点，同为global但没有subPage的autoTakeVipPrivilege模块，拿到的kind为other，但此模块拿到的kind为global

以下错误堆栈：
Uncaught TypeError: Cannot read property 'map' of undefined
    at n.t.handleSetSetting (config.js:378)
    at onClick (config.js:490)
    at Object.<anonymous> (vendors.bundle.js:34385)
    at f (vendors.bundle.js:34389)
    at vendors.bundle.js:34395
    at _ (vendors.bundle.js:34400)
    at at (vendors.bundle.js:34949)
    at it (vendors.bundle.js:34943)
    at st (vendors.bundle.js:34955)
    at ht (vendors.bundle.js:35013)

**Comment by jjj201200** [comment]
你应该使用other或者约定一个新的名为home的kind name而不是使用global
然后我看不到你是怎么写这个模块的，除非你提供一个最小化可以复现问题的版本，不然我没办法给你解答

**Comment by memorydream** [comment]
> 你应该使用other或者约定一个新的名为home的kind name而不是使用global
> 然后我看不到你是怎么写这个模块的，除非你提供一个最小化可以复现问题的版本，不然我没办法给你解答
> 
> 我能说明的是，你应该能够在config.js里看到默认的kind初始化对象，并且逻辑显示会把没有匹配到的都算在other里，所以显然，global也算other。
> 
> 然后更显然的是，在页面注入时，它会被pages里的global加载并得到执行。因为global在manifest.json里就是这么配置的。所以你不应该将其kind设置为global，设置为other是合适的。如果将来b站首页有更多功能，可以约定一个独立的名为home的kind。

我已经在我的fork中添加了一个复现bug的分支
https://github.com/memorydream/bilibili-helper-o/tree/bug-report

**Comment by jjj201200** [comment]
在这里存在一个缺陷，类似的问题应该都存在
https://github.com/memorydream/bilibili-helper-o/blob/546cd0ae5738b23da229d7de470434e6717f3457/src/js/pages/config/index.js#L200

如你所见，由于目前other下的所有功能都没有配置subPage，所以该缺陷没有被发现，将其修复即可

此外我认为暂时没有必要特地为一个功能开一个新的kind，至少两个及以上再考虑比较合适，当然我只是建议。

**Comment by memorydream** [comment]
> 此外我认为暂时没有必要特地为一个功能在设置页面开一个新的kind，它会自动将home归类为other，两个及以上再考虑比较合适，当然我只是建议。


我认为这个建议是合理的，我会将这个功能放在other下

**Comment by memorydream** [comment]
#778
