### ISSUE TITLE
bug：直播间版聊模式导致聊天面板被错误遮盖

### ISSUE THREAD

**Issue by memorydream** [bilibili-helper/bilibili-helper-o#779]
1. 操作系统 (Windows/macOS/Linux): Windows10/Linux
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):Vivalid(Windows)   Edge(Linux)
3. 扩展版本:1.2.24(windows)   1.2.24.2beta(linux)

### 重现步骤/尝试的解决方案
打开直播间的版聊模式，并进入网页全屏
退出网页全屏，关闭版聊模式（一定要先进入一次版聊模式）
再次进入网页全屏，播放器会覆盖整个页面，本应在右边显示的聊天面板会被播放器遮盖

代码变化：
进入版聊模式时，body会被附加上一个hide-aside-area的class，关闭版聊模式后这个class没有被删除

**Comment by jjj201200** [comment]
@memorydream 版聊模式在功能设计上是进入网页全屏后会自动关闭侧边弹幕框的，并且这个框的显示与否本来就不会因为播放器显示状态而变化
如果你需要显示侧边弹幕框，就没必要打开版聊模式。
我们暂时不修改这部分逻辑哈。

如果有更多用户有相同的问题，我们会考虑将其改为「还原」而非现在的「保持」。

**Comment by memorydream** [comment]
> @memorydream 版聊模式在功能设计上是进入网页全屏后会自动关闭侧边弹幕框的，并且这个框的显示与否本来就不会因为播放器显示状态而变化
> 如果你需要显示侧边弹幕框，就没必要打开版聊模式。
> 我们暂时不修改这部分逻辑哈。
> 
> 如果有更多用户有相同的问题，我们会考虑将其改为「还原」而非现在的「保持」。

我认为这是个单纯的逻辑和描述问题，当我打开了版聊模式，之后因为某些原因我又不想用了，这个时候我希望通过点击“关闭版聊模式”按钮可以回到最开始行为，而不是保持隐藏右侧弹幕框
如果这是个特意为之的行为，那么它需要更为明确的描述，告知用户这是一个刻意的设计，而不是一个可能的BUG
更进一步，可能需要为这两种需求制作独立的开关

**Comment by jjj201200** [comment]
@memorydream 不会为所有情况做处理，不会为所有情况都做详细的说明
