### ISSUE TITLE
i18n在edge中的bug

### ISSUE THREAD

**Issue by memorydream** [bilibili-helper/bilibili-helper-o#784]
edge中的语言选项有两种情况：
以这种语言显示Microsoft Edge；
该语言位于列表最上方；

在Linux中不存在 “以这种语言显示Microsoft Edge” 选项

以下为该Edge特殊行为导致的BUG：
插件的i18n以浏览器的显示语言为准
bilibili以 navigator.language 为准，在edge中，navigator.language的值为列表最上方的语言

**Comment by memorydream** [comment]
![edge i18n bug](https://user-images.githubusercontent.com/34763046/97514876-c25e9a00-19ca-11eb-80a0-263eefc04a7f.png)

![edge i18n bug 2](https://user-images.githubusercontent.com/34763046/97514873-c094d680-19ca-11eb-9f02-407489e29378.png)

**Comment by memorydream** [comment]
该BUG导致的情况：
在屏蔽主页分区这个功能中，以侧边导航栏中的innerText为key用以定位实际要屏蔽的元素；
（该innerText的匹配在该版本中被错误的硬编码为简体中文，下一个版本中修复）
bilibili实际显示繁体，但是插件使用的key依然为简体中文，导致无法成功匹配到需要的元素；

目前的解决方案：
在该模块中硬编码简中与繁中方案，实际使用navigator.language匹配对应方案

注：在使用此方案前，有修改为__()匹配的方式，该方式具有以下两个问题：
    在edge中，可能错误的使用了繁中，但是插件依然运行在简中下，导致匹配错误;
    在其他浏览器中，因为bilibili不支持英文主页，可能实际导致匹配错误

**Comment by jjj201200** [comment]
了解了，那我们干脆对语言问题做一次修改吧

**Comment by memorydream** [comment]
> 了解了，那我们干脆对语言问题做一次修改吧
> 
> 看一下`chrome.i18n.getUILanguage()`这个接口在linux下的的返回值

在edge for linux下，皆返回zh-CN

**Comment by memorydream** [comment]
经测试，在B站首页，chrome.i18n.getAcceptLanguages()返回值中的第一个值匹配正确

**Comment by jjj201200** [comment]
@memorydream 好的，不过这个结论没用，因为i18n这个对象没有set接口，只有get，我正在写语言切换模块，你那边就暂时那么处理吧

我们这几天再上一个版本解决一下这个问题

**Comment by jjj201200** [comment]
@memorydream 你测试用的Linux下的Edge是什么版本的呀，会不会是版本差异

**Comment by memorydream** [comment]
> @memorydream 你测试用的Linux下的Edge是什么版本的呀，会不会是版本差异

linux下只有dev版本，但是和windows上edge的结果应该是一致的，我现在去测试以下

**Comment by jjj201200** [comment]
@memorydream 我mac下的edge（84.0.522.49）是没有这个「Microsoft Edge 以此语言显示」的，和 mac下的chrome一样

**Comment by memorydream** [comment]
> @memorydream 我mac下的edge（84.0.522.49）是没有这个「Microsoft Edge 以此语言显示」的，和 mac下的chrome一样

那就是只有windows有这个选项了
