### ISSUE TITLE
能否添加一个“打开视频网页后自动播放的功能呢”

### ISSUE THREAD

**Issue by hualuoshuijia** [bilibili-helper/bilibili-helper-o#789]
通常情况下   打开想看某个视频  点击后打开新的标签页  视频是不会自动播放的   需要自己点击视频才可以播放  

不知是否能添加  先在此谢过，能有这插件可以免费用，多谢。

打开视频后 不是自动播放需要手动点击才可以播放。
![image](https://user-images.githubusercontent.com/49584289/98488565-fa849900-2264-11eb-858e-b1bf1ef7bcff.png)

**Comment by jjj201200** [comment]
按下图所示设置一下哦
![image](https://user-images.githubusercontent.com/3397549/98513030-312cd480-22a2-11eb-9547-38e3f04e188d.png)
