### ISSUE TITLE
1.2.25版本，插件无法登陆

### ISSUE THREAD

**Issue by circlewind** [bilibili-helper/bilibili-helper-o#791]
## 问题反馈
在您提交问题前, 请检查以下项目:
- [x] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [x] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): Windows10
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): Chrome 86.0.4240.198
3. 扩展版本:  1.2.25 (stable)

### 重现步骤/尝试的解决方案
在主站登陆后，插件显示未登录，所有需登录的功能无法使用。
尝试了在主站主站登出后重新登入，插件显示需要重新加载，点“重新加载”后依然显示未登录
尝试了从谷歌商店重装，无效

**Comment by circlewind** [comment]
手动下载安装了1.2.24版本后，可以正常登陆了。似乎是1.2.25版本问题。

**Comment by jjj201200** [comment]
不是个别版本的问题，请装回1.2.25，如果碰到这个问题，重新登录一下b站好账号就好了
