### ISSUE TITLE
插件下载的xml弹幕无法播放

### ISSUE THREAD

**Issue by MOIX-1192** [bilibili-helper/bilibili-helper-o#794]
## 问题反馈
使用本地弹幕播放软件（bililocal,dandanplay)无法加载xml弹幕

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):win10 教育版 1909
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):Microsoft Edge
版本 86.0.622.69 (官方内部版本) (64 位)
3. 扩展版本:1.2.24

### 重现步骤/尝试的解决方案
见附件
[附件.zip](https://github.com/bilibili-helper/bilibili-helper-o/files/5571025/default.zip)

**Comment by jjj201200** [comment]
请发一下视频地址

**Comment by MOIX-1192** [comment]
> 请发一下视频地址

www.bilibili.com/bangumi/media/md28230900

**Comment by jjj201200** [comment]
请问你的正常样本是哪里来的？

**Comment by MOIX-1192** [comment]
> 请问你的正常样本是哪里来的？
[JJDown](http://client.jijidown.com/)网页版不知道为什么不行，客户端可以下。不过，它下载的弹幕只有前90分钟。

**Comment by jjj201200** [comment]
已经修复了，一会儿会发测试版在测试群里，感谢你的反馈~

**Comment by jjj201200** [comment]
@MOIX-1192 目前b站所能加载的弹幕数量有上限，所以就是这样的啦~

**Comment by MOIX-1192** [comment]
> @MOIX-1192 目前b站所能加载的弹幕数量有上限，所以就是这样的啦~

好的，谢谢

**Comment by jjj201200** [comment]
issue得先开着哈，等正式版审核过后我会关掉的

**Comment by jjj201200** [comment]
1.2.27版本已经上架，记得更新~
