### ISSUE TITLE
可不可以把稍后再看功能做到外面而不是二级页面。想要增加封面图片查看的功能。

### ISSUE THREAD

**Issue by shishirong** [bilibili-helper/bilibili-helper-o#795]
## 问题反馈
- [ ] 稍后再看是我用的高频率的功能，可是每次都要去二级页面找，还是稍微繁琐了一点。要是直接就显示在外面可以点击就好了。
- [ ] 有的up主的视频封面图是精心做的，里面可能包含了有用的信息，所以想要增加封面图片查看的功能。

> 之前我都是用的油猴脚本来实现这些功能的，现在想要做到bilibili-helper中，以免油猴太臃肿。油猴脚本如下
> 1. [封面图脚本](https://greasyfork.org/zh-CN/scripts/33411-bilibilicover-%E8%8E%B7%E5%8F%96%E5%B9%B6%E6%98%BE%E7%A4%BAb%E7%AB%99%E8%A7%86%E9%A2%91%E5%B0%81%E9%9D%A2%E5%9B%BE%E7%89%87)
> 2. [稍后再看脚本](https://greasyfork.org/zh-CN/scripts/395456-b%E7%AB%99%E7%A8%8D%E5%90%8E%E5%86%8D%E7%9C%8B%E5%8A%9F%E8%83%BD%E5%A2%9E%E5%BC%BA)

### 环境信息
1. 操作系统 (Windows/macOS/Linux):Windows
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):MS-Edge
3. 扩展版本:v1.2.24

**Comment by jjj201200** [comment]
封面图下载之后会加的哈，请放心

至于稍后再看页面，你可以加2.0测试群，我添加了在现有的「主站、直播等」导航下面可以添加自定义导航的功能，想加什么就加什么，可以试试看，群号677639415
