### ISSUE TITLE
视频下载无法自动选择最高清晰度

### ISSUE THREAD

**Issue by szbiao218** [bilibili-helper/bilibili-helper-o#797]
出现这个问题是chrome浏览器突然需要我给插件进行授权，完成授权以后开始出现的问题，不管视频支持什么清晰度，都会选择720p。
chrome版本为87.0.4280.66，插件版本为1.2.26

**Comment by szbiao218** [comment]
确认了一下，是chrome商店自动更新到1.2.26以后出现的问题，卸载换回1.2.25就正常了

**Comment by jjj201200** [comment]
感谢反馈，我这边关掉了所有版本也能复现这个问题，所以我认为这应该不是助手导致的这个问题

这里对新授权的事项做一下说明，增加的授权项是对我所购买的新域名，未来可能会用与官网的域名的授权，而目前这些网站还没有建设，所以不存在安全问题，请放心

我似乎也不记得助手中并没有有过对清晰度的处理

**Comment by szbiao218** [comment]
那就很怪了，不知道是我浏览器的版本问题还是别的原因，26就算视频打开后自动选择了1080+，点下载弹出的标签里视频清晰度也是720p，需要手动再点一下视频清晰度，下载的清晰度才会跟着改变。只能先用着25了

**Comment by jjj201200** [comment]
清理一下localStorage缓存，就好了，我这边解决问题了，你是否还同时使用了别的扩展或油猴脚本？

**Comment by szbiao218** [comment]
清了缓存关了所有插件还是不行，可能是个例。重启以后打开chrome会自动更新到26，可能是商店给自动更新的。大批量下载每次都要重新选清晰度还是挺麻的

**Comment by jjj201200** [comment]
是localstorage，你可能需要去查一下如何清理这个

**Comment by jjj201200** [comment]
我这边测试下来
在关闭任何其他扩展程序和脚本的情况下，可以稳定复现这个问题
过程如下：
1. 清空浏览器的localstorage缓存，不知道怎么做可以百度到
2. 刷新播放页
3. 此时清晰度是auto，切换清晰度到1080p（如果有的话）
4. 刷新播放页
5. 清晰度被锁定在720p，且之后不论怎么改打开的播放页清晰度都会默认是720p

我这边建议像b站反馈，不知道是他们有心这么设计还是确实是bug

**Comment by jjj201200** [comment]
锁清晰度的问题我这边复现不出来了，但是助手默认最高只显示到720的问题修复已经发布在测试群里了哈

**Comment by szbiao218** [comment]
感谢，原锁720清晰度的问题已经解决了
