### ISSUE TITLE
啊，这……

### ISSUE THREAD

**Issue by DarthMikuH** [bilibili-helper/bilibili-helper-o#799]
<img width="1280" alt="截屏2020-11-28 下午2 31 37" src="https://user-images.githubusercontent.com/62818311/100495444-ec041000-3186-11eb-902b-7149df3702f7.png">

**Comment by jjj201200** [comment]
请更新至1.2.26，已经上架了

**Comment by DarthMikuH** [comment]
OK，谢谢



---原始邮件---
发件人: "DrowsyFlesh"<notifications@github.com&gt;
发送时间: 2020年11月28日(周六) 晚上8:16
收件人: "bilibili-helper/bilibili-helper-o"<bilibili-helper-o@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"DarthMikuH"<darthmiku@foxmail.com&gt;;
主题: Re: [bilibili-helper/bilibili-helper-o] 啊，这…… (#799)




 
请更新至1.2.26，已经上架了
