### ISSUE TITLE
新版的助手不能下载弹幕

### ISSUE THREAD

**Issue by Asfrim** [bilibili-helper/bilibili-helper-o#800]
新版的助手不能下载弹幕，已经用回1.2.25版，望作者更新，感谢作者大大

**Comment by jjj201200** [comment]
我这边没问题的呀，方便远程协助看一下吗

**Comment by Asfrim** [comment]
做了个视频，v.youku.com/v_show/id_XNDk4NTkzNzY3Mg==.html，作者大大方便的话看一下也可以，谢谢

**Comment by jjj201200** [comment]
你装了很多扩展，请你用排除法检查一下是什么扩展导致的问题

**Comment by jjj201200** [comment]
![image](https://user-images.githubusercontent.com/3397549/100542857-af6c0d80-3287-11eb-9f8d-10a03b4eeb41.png)

红色的字应该已经足够明显来让你看到了

**Comment by Asfrim** [comment]
红色说权限不够，但是1.2.25版就没有这个提示，一切正常，1.2.25版就是权限够吗，还有后面我装了个全新的QQ浏览器（Chrome内核），也没什么插件，权限也够，但就是不能下载弹幕，点了之后弹幕这个功能窗整个消失了，但换1.2.25版也能下载弹幕，这在视频里都有反映，我准备去换台电脑装个全新的Chrome再试谢谢作者大大

**Comment by Asfrim** [comment]
试过了，换了台电脑然后全新安装的Chrome，然后装1.2.26版，情况跟全新安装的QQ浏览器一样，没什么红字提示，权限正常，但仍旧不能下载弹幕，点了之后弹幕这个功能窗整个失踪，
![Untitled](https://user-images.githubusercontent.com/75174823/100546932-06c9a800-329f-11eb-8d0f-0adce28f68da.png)

**Comment by jjj201200** [comment]
那不用qq浏览器呢？用chrome试试

**Comment by jjj201200** [comment]
emmm这边还是需要你确认一下使用的浏览器的版本

**Comment by jjj201200** [comment]
我建议你登录一下b站账号

**Comment by jjj201200** [comment]
记得更新版本，1.2.27了
