### ISSUE TITLE
能否加入默认关闭「自动播放」并屏蔽这个按键

### ISSUE THREAD

**Issue by CloudyEagle** [bilibili-helper/bilibili-helper-o#802]
### Environment Info
Please fill out the following:
1. Operating System (Windows/macOS/Linux): Windows 10
2. Chrome Version (You can check this under [Menu/Help/About]): Maybe All Browsers
3. Extension Version: 1.2.26

### Steps to Reproduce / Attempted solution
![Snipaste_2020-12-14_15-15-20](https://user-images.githubusercontent.com/58777085/102052415-0691e680-3e21-11eb-9958-e088f410dafe.jpg)
B站虽然提升一点使用体验，在浏览器缓区里建了一个存储是否已关闭，
已便下次打开播放界面，防止仍会自动连播；
但如果清除浏览器缓存好像又要再次点击一旁的开关，希望插件里能集成一个关闭并不现实自动播放的功能。
我想这可以直接集成进2.0版本吧？！

**Comment by jjj201200** [comment]
但你不是会清理掉缓存么？扩展的设置也是同样的原理缓存的啊

**Comment by CloudyEagle** [comment]
> 但你不是会清理掉缓存么？扩展的设置也是同样的原理缓存的啊
> 
> 对于低频的事件我觉得不需要做特别的处理，你不清理不就完事了，不小心清理了再点一下不就好了么，犯不着太纠结于此

是哦，那就算了吧
