### ISSUE TITLE
下载4k乃至1080p功能完全不可用

### ISSUE THREAD

**Issue by DWX256OnGitHub** [bilibili-helper/bilibili-helper-o#803]
![屏幕截图 2020-12-15 224430](https://user-images.githubusercontent.com/68551259/102229824-24e20a00-3f27-11eb-8d64-9a0b9bb1c058.png)
如图所示，观看1080p60fps的视频时插件无法获取到当前视频流的下载地址，只能最高720p60

**Comment by jjj201200** [comment]
请先根据模板描述你的技术信息以便于我们提供帮助

**Comment by 1265578519** [comment]
![image](https://user-images.githubusercontent.com/6442439/102406382-6fe24700-4025-11eb-9748-4207bac4e0b8.png)
