### ISSUE TITLE
B站的直播间UI改版，导致版聊模式已经失效

### ISSUE THREAD

**Issue by yuijker** [bilibili-helper/bilibili-helper-o#804]
### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):Windows
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):360极速浏览器（chrome版本86.0.4240.198）
3. 扩展版本:
1.2.27（正式版）
您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)
今天B站的直播间UI改版，导致版聊模式已经失效。

![image](https://user-images.githubusercontent.com/72558803/102345250-05ef8080-3fd8-11eb-8144-ab2587b19365.png)

![image](https://user-images.githubusercontent.com/72558803/102345299-1c95d780-3fd8-11eb-9e2d-c1dbc90c1bcc.png)

**Comment by jjj201200** [comment]
收到，刚发现了，之后会优先在2.0上实现该功能

**Comment by jjj201200** [comment]
已修复，记得更新
