### ISSUE TITLE
鼠标悬浮在消息或动态上呼出菜单[深色模式/夜间模式]的样式错误

### ISSUE THREAD

**Issue by CloudyEagle** [bilibili-helper/bilibili-helper-o#813]
1. Operating System: Maybe All System
2. Chrome Version: Maybe All Browsers
3. Extension Version: 1.2.27.2
Steps to Reproduce
![QQ截图20210109154419](https://user-images.githubusercontent.com/58777085/104116701-facd0d80-5355-11eb-8e07-4aaacd8d72a5.jpg)
![QQ截图20210109154538](https://user-images.githubusercontent.com/58777085/104116705-fef92b00-5355-11eb-91c1-4a8b05253272.jpg)
请问这将还会再1.2版本修复，还是再2.X一步到位

**Comment by Cotch22** [comment]
这两处并非直接渲染的内容而是iframe打开了一个网页，目前的深色模式的能力无法将样式注入到iframe当中，2.*后可能会提供解决办法，比如直接重写这部分的popup，敬请期待。
