### ISSUE TITLE
默认选择最高清晰度

### ISSUE THREAD

**Issue by Compartany** [bilibili-helper/bilibili-helper-o#819]
如题

**Comment by jjj201200** [comment]
直播吗？还是啥？

**Comment by Compartany** [comment]
普通视频啦，油猴上找了几个脚本都不行

**Comment by Cotch22** [comment]
B站视频播放器的清晰度等设定是以浏览器缓存保存的，助手的设定也是基于缓存，B站的登录和注销操作也会影响播放器缓存，如果你不主动清除缓存，你的清晰度选择就不会变。

**Comment by jjj201200** [comment]
@Compartany 2.0清单里已经列出来了哈，未来会添加的，1.x不加新功能了，这个issue我就关了哈
https://shimo.im/docs/ypGHYjwdwrv3hXr9#anchor-c4vl

**Comment by Compartany** [comment]
> B站视频播放器的清晰度等设定是以浏览器缓存保存的，助手的设定也是基于缓存，B站的登录和注销操作也会影响播放器缓存，如果你不主动清除缓存，你的清晰度选择就不会变。

问题就出在清晰度选择不会变上。大部分视频都只有【1080P 高清】这一档，此时切换到有更高画质如【4K】的视频，它还是会选择【1080P 高清】，用户也根本意识不到还会有更高画质。即使你手动切了，一旦在其他低画质视频播放一次，又 TMD 被改回去了。【自动】就更蠢，总是低估用户网速给你选个【720P】。
