### ISSUE TITLE
关于版本号与分发途径的提议

### ISSUE THREAD

**Issue by baobao1270** [bilibili-helper/bilibili-helper-o#823]
我注意到最近 Chrome 商店推送了助手 2.0 的 beta 版本，#697 中也提到了开源版本和闭源版本的分离。

个人认为，升级到 2.0 版本造成了 broken change，希望将 1.x 和 2.x 作为两个独立的插件上架 Chrome 商店。或是将开源版本和闭源版本分为两个插件上架 Chorme。

希望您的回复，谢谢！

**Comment by jjj201200** [comment]
你好，这几天正好发烧卧床2天，没有看到，回复慢了，抱歉啊。2.0目前是处于beta中，目前有少部分用户收到了更新推送。这两个版本确实存在根本上的不同，但是设计理念是一贯的。

作为从若干年前开始维护本项目的主要贡献者，我想首先必须很负责的在这里承认，目前2.0.6版本必须登录后才能使用的设计是粗糙的，与1.x相比是突兀且没有必要的，从2.0.7版本开始将取消这一限制。只在必要的时候，即涉及到需要存储用户数据的相关功能时才提示注册助手账号并登录。

从我发布关注开发者动态到目前为止，从2020年12月31日在b站发布第一篇专栏文章开始，从我发布第一个2.0测试版开始，已经收到了很多很多用户的反馈，有不少认为不合理的设计已经被调整甚至删除，有不少地方被提出需要优化和改进或已经妥协。

在上述基础上，但凡对于那些用过了2.x的用户，我想broken change只在于”我们只需要一个按钮而不是一个APP“这个话题上。

从0.x版本一路维护到现在，不仅仅是用户对这个项目和软件进行筛选，我们也在对用户进行筛选。

另外，正如 #697 所说但是你所误解的，1.x与2.x不仅是向下不兼容的大版本更新，而且是投入成本完全不同的两个版本。1.x不再是重点维护的一方，只在2.x上架前做必要的修复。

关于分版本发布的话题

我们当然是允许其他开发者将修改版本通过除了应用商店以外的途径传播，因为一直都是开源状态，但是1.x版本不应该出现在应用商店，从0.8跳到1.0姑且没有，从1.x跳到2.0也是一样，都是我本人亲自操刀，更何况2.0版本我花了相当大的时间和心力在上面。禁止的理由我想无非需要用户对稳定维护的支持以及对新产品的认可。

如果说不同版本间差异锁提现的理念和供需不同，那将改为商业软件这件事是不是是需要用户首先去接受的呢。

助手有60-70%的用户为老用户，目前2%灰度发布的举措一方面是服务端的调整需要，更大程度上是出于对大多数老用户在使用体验上谨慎的考量，希望你能理解。

最后，如果可以具体描述一下你的核心关切，这有助于帮助我们更加了解一部分用户的想法，我不会毫无理由的不做妥协或作拒绝姿态。

**Comment by baobao1270** [comment]
我实际上被商店推送 2.x 版本后，不登录无法继续使用的现象搞蒙了，情绪比较激动，因此来这里提了 issue。

正如你所说的，我在事实上属于只需要一个按钮而不是一个APP的用户。从两年前开始使用哔哩哔哩助手，重度依赖的功能主要是以下三个：
 - 直播开播通知
 - Up 主更新通知
 - 直播去污粉

因此，我想要的是一个能够直接在 Google 商店获得的 1.x 版本的 Bilibili Helper。我不必付出额外的学习成本去学习 UI 的变动，也不必去注册账户。

恕我直言，使用灰度测试的方式推送新的版本是较为激进的行为。2.x 版本作为一个依赖服务器的版本，现在使用与 1.x 相同的插件 ID 推送，对于只需要本地插件而无需服务器功能的用户来说，就是使用体验的破坏。由于 Google 的政策限制，在 Chrome 上安装非商店应用扩展是非常麻烦的，这也意味着 Chrome 用户将被「强制更新」到 2.x 版本。作为一个开源项目，固然要求它必须上架 Google 商店是不合理的，但是如果您出于对大多数老用户在使用体验上谨慎的考量，使用新的插件 ID 来分发 2.0 版本，而旧的插件 ID 不再更新，是不是更好的解决方法呢？

现在 2.x 版本已经进行了灰度测试，我想我也不能无理地要求将已经发布的 2.x 版本回退，再重新上架。

因此我希望能够在 2.x 中提供「关闭所有依赖服务器的功能」的设置选项。Bilibili Helper 1.x 是一个很棒的插件，我也相信 2.x 能够更好，因此我愿意付出更多的学习成本。但是，作为程序员，想必我们都对大企业软件产品的频繁改版、强制更新、隐私滥用深恶痛绝。本人作为一个有一点”隐私洁癖患者“，对收集数据与账号注册比其他用户更为敏感。并非对你们不够信任，但是引入数据收集与账户功能，则必然会承担面临黑客攻击、数据泄露的风险。因此，如果没「关闭所有依赖服务器功能」的设置选项，像我这样的用户则必定要面临承担隐私风险与离开的抉择。

此外，倘若 1.x 能够作为另一个插件 ID 在 Chrome 商店上分发，给我这样的「怀旧用户」一个获取的渠道，那就再好不过了。

最后，愿您早日康复，新年快乐！

**Comment by jjj201200** [comment]
兄弟，世界上非零即一的好事没那么多，但我愿现存的所有善意天长地久。

我们2.0在做2.x灰度，说较为激进大概是因为让你觉得数量仍旧太大以至于你遭殃了。但是我们正是需要听到大家不同的声音，同时控制在一个合适的人数范围内，目前2%的灰度已经跑满了。

大多数用户都只是觉得我只管用就好了，不需要关心新版本。只有一小部分人关注了我b站账号并参与了前期的建议和反馈过程。这无可厚非，非要说不是的话反倒是我这边的宣传力度还是不够。

我再强调一下，不仅仅是用户对这个项目和软件进行筛选，我们也在对用户进行筛选，任何时候，都是如此。

不存在「用户需要的就是合理的」的绝对正确，不存在非一及零的简单准则。在我的立场上，「合理」只是一种平衡利弊的指标，就像我同意去掉注册并登录才能使用一样，我认同你的这个诉求，因为这个决定目前「从数据而不是用户反馈」来看，不利于软件生存。

提供「关闭所有依赖服务器的功能」的选项肯定是不合理且不可接受的，你考虑隐私，考虑安全性，可以不注册，不使用付费功能，不开启需要服务器的功能，但是需要同意允许搜集软件使用数据等匿名数据，我们当然也有义务去增强软件安全措施。用户需要在使用前同意允许搜集匿名的软件使用数据，否则无法使用。

同时你也应该看到，除了密码和用户的B站UID之外，没有要求用户提交任何其他个人隐私信息。而保存的其他数据也都是助手的功能设置数据。

你也是开发者，理应知道提交软件使用数据是对一款软件长期经营起码的支持。使用并提供诸如「公告」「通知」「警告」「版本控制」等必要的功能也是软件运营商应该具备的能力。

最后，助手2.0还在调整，很多都还未确定。但不会走回头路这点是确定的，未来我会增加更多和1.x类似的开关选项，但出发点一定不是「让现在每一位用户都满意」，绝对不会存在「你需要我就做」的单方面服务，如果有人愿意这么做，我祝愿他能够一直坚持下去不要放弃。

如果你有其他诉求可以在此继续提出

**Comment by jjj201200** [comment]
之前写了一大段话，后来我删了。
我想请问兄弟以及所有认同你观点的人，我这么做了之后可以得到什么。可以从短期中期长期来谈谈吗。我只看到了义无反顾的索取

**Comment by zacyu** [comment]
新年快乐，各位！

作为 bilibili-helper 项目最初的作者，我也想在这边谈一下我关于这个提议，以及更广泛的讲，关于 2.0 版本中加入的需要登录帐户的功能 (#822) 的看法。

关于这个 issue 中的提议，我想从在 #697 中提到的从 2.0 版本开始发布包含私有代码的闭源版本的决定说起。因为这个决定的前提和理由已经在前面提到的 issue 中具体说明, 我在这边只想提供进一步的背景：2.0 版本从 2020 Q2 构思，到原型制作，争取意见，2020 Q3 + Q4 代码实现（字面意义上的从头开始重建），封闭的内部测试，以及最近开始进行的梯度公开测试，@jjj201200 作为项目**唯一的**维护者，一人实质上肩负软件工程师，产品经理，测试工程师，和公共关系经理的职责，投入了大量的时间和精力来构建一个更加成熟的作品（无论是工程上还是产品上）——尊重用户的声音（如 2.0 版本保留几乎所有现有功能）的同时，也尊重我们面前的机会（如新增的由服务器支持的功能）。

在打造 2.0 版本的同时，我们也一直在将 1.x 版本作为处于维护模式的产品针对 B 站的更新而不断提供错误修复和性能改进，其中许多都必须在两个分支中重复。从前面提到的 issue 发布到现在，我们花费了 8 个月的时间。在此刻 2.0 版本开始逐渐分发给用户的之际，我认为像提议中所述，让我们**同时维护两个版本分支的开发**（你的提议暗示了这一点，我想）并在 Chrome 应用商店分别发布的请求，是很难满足的。如果你对 2.0 版本的变化不满意，并想要贡献时间和精力来维持 1.x 版本功能的发展，我们欢迎你 fork 当前的代码库并基于此开发并在非应用商店的渠道上发布。如果 1.x 版本分支的持续维护进展顺利，我们甚至可以讨论由我们将分支在 Chrome 应用商店上发布的合作的机会。

接下来，关于你和 @1265578519, @shikibu-z 等其他用户所在意的需要登录帐户才可以使用功能的问题，我也认为限制不需要服务器支持的功能（如大多数从 1.x 版本中继承的，提供免费使用的功能）和我们尊重用户的初衷是相悖的。我在了解到个问题后和 @jjj201200 讨论过这种做法的必要性，现在也看到他在上面的回复中提出将从下一个版本开始取消这一限制的决定。我的理解是取消这一限制后，没有登录帐户的用户（安装/升级到 2.0 版本后的初始状态）将无法使用需要服务器支持的功能（即你提到的「关闭所有依赖服务器的功能」）。**我们欢迎你和其他有类似考量的用户继续提出对我们的隐私保护做法**（见《隐私协议》）的顾虑和建议。我也希望你们也可以理解我们为了产品开发（如主动检测兼容性错误和调整功能维护/开发优先级）对匿名化的用户使用数据（如运行时错误和功能使用频率等）的收集的需求。对于在 Chrome 应用商店上分发的版本，我们目前还没有计划提供让用户选择退出这些使用数据的收集的选项。如果你们对这部分数据的收集仍然存在顾虑，可以选择基于开源的版本（2.0 版本对应的开源版本分支将在分发达到 100% 后发布），维护去除所有数据收集代码的分支。类似的，我们欢迎你将该分支在非应用商店的渠道上发布。

需要说明的是，由于时间所限，我目前已经不再积极地参与 bilibili-helper 项目的开发。我希望在这里再次感谢 @jjj201200 可以将这个从最初只提供样式更改的个人玩具发展来的项目持续维护下去，带领从 0.8.x 到 1.x 以及到 2.0 新版本的迭代开发并不断听取用户的声音。我希望这个回复可以更清楚的阐明我们的考量，也同时欢迎更多的开发者参与到我们的开源项目中（包括参与到新功能/变化的早期讨论中）。我今后也将尽我所能，为了项目的顺利发展提供支持。

**Comment by 1265578519** [comment]
https://github.com/bilibili-helper/bilibili-helper-o/releases/tag/v1.2.30
在这下载1.2.30版本，通过crx安装到chrome，1个小时后，还是被强制推送到2.0升级，我认为楼主说的有必要，分成两个id，这样才可以正常使用旧版本

**Comment by jjj201200** [comment]
1. 如果愿意帮助维护1.x版本，可以联系我并提交代码上来，我去开一个新扩展（以新ID），只署贡献者的名（可以多个）；
2. 可以自己fork自己build，碰到问题尽管问我，build成功后打开chrome开发者模式，加载已解压扩展程序；
3. 如果没人愿意持续贡献，又想要用1.x。请做选择题，这很公平。

我认为这已经仁至义尽，各位三思而后行。

**Comment by zacyu** [comment]
Please side-load non-release/unofficial versions (including old and
pre-release versions) from unpacked in the Developer mode.

**Comment by 1265578519** [comment]
build什么的我们不懂，我试试开发者模式安装crx看看会不会被强制升级

**Comment by baobao1270** [comment]
Re: @jjj201200 

开源软件的现状即是，开发者除非获得捐赠、资助，难以获得除了声誉之外的回报。

我们的立场与理念不尽相同，我也并非强求您的一味付出，只是希望能够通过交流达成一致。

我理解您作为一个拥有一定用户群体的软件的开发者，需要对大多数用户负责，也有理由为软件的存续做出任何决定。作为用户，我们的立场仅仅软件要是满足自己的需求。当立场冲突时，我们也只能平衡、取舍，以取得最大公约数。

我认为作为用户去提出一个需求，一个 Feature Request，应该阐述期望的功能并解释为什么需要这个功能。而「这个功能能够我/我的软件带来什么」，是软件维护者应该考虑的事情。您可以在考虑后，回复我「这个需求可以实现」或是「不会去实现」，又或许是「今后可能会实现」，并选择附上或不附上理由。指望所有用户站在他们的立场去思考他的需求会给开发者带来什么，是不现实的。这只有少数用户能做到。

至于「倘若 1.x 能够作为另一个插件 ID 在 Chrome 商店上分发」，站在用户的立场上，有人需要即是理由。而我也承认，开发者是没有理由您作为开发者在这件事上是难以获得任何利益的。

最后，我依然要指出，我强调自己的需求，只是为了能够通过交流达成自己的目的，并非在强求您需要做什么。如果经过您的判断，我属于被您筛选掉的用户，那么我们只能说一声珍重，而相忘于江湖。

以下是对于您 18:47 的回复：

首先我愿意帮助向 1.x 共享一些代码，但无法承诺持续地维护。当然，我认为持续的维护不是以新 ID 上架商店的必要条件。目前 1.x 的最新版本是可用的，这就足够了。今后的维护可以交给社区，如果社区难以维护亦可停止更新。

-------

Re: @zacyu 

我想我的语言可能造成了您的一些误解，我并未要求你们同时维护两个版本之意。我仅仅希望是能够在 Chrome 商店上获取到 1.x 版本。你们可以选择自己维护，或是交由社区维护，或是停止维护与更新。我希望能够通过 Chrome 商店获取的原因，也主要在与 Chrome 对于非商店扩展的严格限制导致了安装 CRX 文件及其困难。

-------

Re: @1265578519 

请问您是如何安装 CRX 的，我 Chrome 88 已经无法安装了，只能开发者模式，谢谢！

------

最后，说一些我的个人看法，这些看法具有一些主观性，也或许与 @jjj201200 的理念相悖。当然，我的这些观点并非在抨击或批评谁，也并非论证我一些「无理要求」的合理性，仅仅是一些个人主观的想法。

第一，相信您也收到许多用户对于强制登录的反馈了。但是您认同你的这个诉求，是「从数据而不是用户反馈」来看，我认为这仍然有失偏颇。我并不认为用户的一切要求都是合理的，但是如果某项改动引起了相当一部分用户的反对，是否应该进行一些考虑呢？

第二，我承认数据的收集对于软件的开发改进具有一定的意义，但是并不是没有匿名数据收集，软件就做不好了。大多数软件都有关闭数据收集的功能，很多 GNU 软件也都没有任何数据收集功能，但是它们依然十分优秀。

第三，我并不清楚闭源版本的 Bilibili Helper 的开发流程，也不可能知道其代码结构。但是我想，如果有着良好的程序设计和代码风格，那么 1.x 和 2.x 的代码本身就是兼容互补的。那么同时维护 1.x 与 2.x 就不必维护两套代码，而只需要维护其增量部分。社区对 1.x 的贡献也能简单地移植到 2.x 上。

-------

我相信我们的讨论已经有了结果，在之前的讨论中，我已经将我的需求与原因进行了解释。

如果你们认为「1.x 能够作为另一个插件 ID 在 Chrome 商店上分发，并随缘更新维护」可以接受，那么我也愿意向 1.x 贡献一些代码。

如果你们认为在没有维护者接手的情况下，「1.x 能够作为另一个插件 ID 在 Chrome 商店上分发，并随缘更新维护」是不可接受的，请回复我并 close 这个 issue。

在这种情况下，按照我的理解，fork 本项目并进行一些修改，使用非 Bilibili Helper 的名义以相同许可证在 Chrome 上发布是被许可证允许的。那么我会将本项目的 1.x 版本 fork 后用 TypeScript 重写一遍，按照自己的理念进行修改，并以自己的名义、不同的名称、相同的许可证在商店上发布，当然也会提及本项目的贡献。如果我对许可证的理解有误，敬请斧正。

再次声明，我并无强求开发者怎么做，只是希望能够通过交流达成我的需求。倘若选择了陪伴，那么大家都应做出相应的妥协；倘若选择了分道扬镳，那也希望能够好聚好散。

**Comment by Cotch22** [comment]
既然你是开发者，那么你一定很清楚当今软件市场，优秀的软件都是被更新推动的，相信你不会坚持使用一个长期不更新的软件。当然很多独立的项目在更新时，保留“老版本”的获取途径，可能是怀旧，也可能是有的用户更喜欢留在过去，但我的主观判断告诉我，这是不对的，即使“老版本”已经相对稳定，但是它无法适应之后的变化，或者有潜在的问题无法被尽快照顾到。

比如2014年之前的微信没有红包能力，如果你坚持使用老版本，那么你如何收取2021年别人发给你的红包呢。

作为开发者，希望的是把自己认为正确的优秀的体验交给用户，如果用户不满意，那么我们会努力让用户满意，而不是回到做出改变前，或者是做不必要的妥协。

使用开发者模式加载解压后CRX安装的插件是不会和商店下载的重叠的，两者可独立存在与你的Chrome，但你只能同时开启一个，否则会因为功能重叠造成不必要的麻烦。但是我非常不建议这么做，我们应该去接受新的事物，如果它不和你心意，你尽管提出你的想法，难道这不就是“开发”的意义吗。

**Comment by jjj201200** [comment]
我去安排1.2.30版本以新ID上架，但是名字会改一下，大概还是「TOTORO：bilibili.com 综合辅助扩展」之类的，之后2.0也会改成类似的名字。因为之后还要注册商标什么的一大堆事，避免不必要的版权上的麻烦。

你我他在这issue里打了那么多字，想必应该都清楚各自不是什么专横不讲理的人。
之后我们尽力维护吧，人在做天在看。

最后解释一下什么叫做「从数据而不是用户反馈」。显然「从数据而不是用户反馈」并不是指完全不考虑用户反馈，因为幸存者偏差效应是常见的。我不可能在数十万人堆里因为只听到1000人说NO就直接采纳这些人的说法。数据可能误读误判，通常也最能代表事实。

**Comment by jjj201200** [comment]
顺便提一嘴，正是因为需要缩小幸存者偏差效应，所以才更加需要服务端的支持，以拉近运营和用户的距离，得到尽可能快速和真实的反馈，2.0中已经增加「公告」，之后还有「小调查」这种一次单个的单选小问卷。现实中往往十万人里有那么几个人发声就已经不错了。

**Comment by 1265578519** [comment]
我通过chrome开发者方式安装crx扩展，还是被商店强制推送升级了，到底怎么搞才能用旧版本？

**Comment by Cotch22** [comment]
> 我通过chrome开发者方式安装crx扩展，还是被商店强制推送升级了，到底怎么搞才能用旧版本？

解压crx后使用“加载已解压的扩展程序”按钮进行导入

**Comment by 1265578519** [comment]
@Cotch22 你那能用吗，我这试了下不起效果
![image](https://user-images.githubusercontent.com/6442439/109394218-d6a6a980-7960-11eb-9a77-5beaf933b4e8.png)
![image](https://user-images.githubusercontent.com/6442439/109394220-d9090380-7960-11eb-9cdb-2a8f9666c5d6.png)
![image](https://user-images.githubusercontent.com/6442439/109394223-db6b5d80-7960-11eb-971c-87205aac03b0.png)

**Comment by lb-chc** [comment]
或许可以将服务端也开源, 供用户选择自建还是使用官方(你们)用同种代码搭建的服务端? 依赖服务器的同步功能完全可以做成网盘WebDAV协议或更新本地文件供用户自行同步的形式,就像开源笔记软件Joplin一样

想商业化的话自然没什么可说的了,但无此考虑的话完全可以不做这种脏事,依然把权力交给用户,不去当那个大家长啊

**Comment by lb-chc** [comment]
而需要24小时即时爬取的依赖服务器功能(开播通知?)同理也可以放在开放的服务端程序里, 登陆仅作避免滥用浪费服务器资源之用

并且依托你们的用户量完全可以号召志愿者进行分布式采集, 让志愿者完成其他用户提交的监听需求, 就不需要登陆了, 或者以一种匿名识别符像pt一样通过贡献价值量获取基本信任以避免过度提交任务的攻击和滥用, 并以此换取他们所需的即时数据,这样不就匿名又无需开发者负担过大的服务器开销了吗?甚至你们可能都不需要进行彻底的中心化调度,而是交给老用户的对等服务端互相监督检查数据投毒就行了......?

这样整个项目就属于社区, 没有团队独裁的隐患了, 你们也不需要为了封闭还是开放而扮演恶人了
