### ISSUE TITLE
[建议]在Readme中表示目前对火狐版本开发的意见

### ISSUE THREAD

**Issue by Neubulae** [bilibili-helper/bilibili-helper-o#827]
毕竟少点issue也少点工作量啊…

**Comment by Neubulae** [comment]
https://www.extensiontest.com/test/88d2c4d0-7d1d-11eb-8153-b33136a67716
另外 最新crx文件扔进火狐兼容性测试的返回结果是绿灯，也就是你甚至只要立刻放到火狐官方插件仓库就是立等可取状态……
虽然自动化设施似乎不大对胃口？

**Comment by Neubulae** [comment]
啊，除了icon must be square

**Comment by jjj201200** [comment]
最新版本有做火狐的基础适配，但是介于之前6个月的审核过程，目前没有发布到火狐的计划。大多数火狐用户会自行发布不可见的版本（即不会在商店展示的版本）来自己用。十分抱歉才看到这个issue。

**Comment by Neubulae** [comment]
好的，我也自己搞了（
