### ISSUE TITLE
能否阻止bilibili播放器获取小CDN地址从而提高缓冲速度？

### ISSUE THREAD

**Issue by JedSunCN** [bilibili-helper/bilibili-helper-o#829]
## 问题反馈
B站目前在联通网络环境下会尝试连接星域CDN获取Video和Audio流，这样会导致中途时间点直接访问卡顿以及快进卡顿（此类CDN经体验为小水管）。能否阻止B站播放器获取这类CDN，使用大型服务器（不用指定供应商）作为服务器？谢谢！

![20210314213025](https://user-images.githubusercontent.com/41063651/111071680-4052b600-8512-11eb-8ac6-1000da58bef6.png)

**Comment by JedSunCN** [comment]
还有一点，现在发现B站疑似开始使用hcdn技术，导致播放时后台占用带宽。虽然可以使用WebRTC Leak Prevent来阻止，请问能否在助手插件中增加此类选项来阻止后台静默上传？

**Comment by jjj201200** [comment]
那，老实说这种行为的功能我觉得不太适合加载助手里，对助手来说有太大法律风险。不过应该是能做到的，可以用助手1.x框架快速的写一个。

**Comment by JedSunCN** [comment]
好吧，感谢解答🤣
