### ISSUE TITLE
不定期的功能失效/版本异常

### ISSUE THREAD

**Issue by yuban01652** [bilibili-helper/bilibili-helper-o#833]
问题反馈
在您提交问题前, 请检查以下项目:
- [√] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [√] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [...] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [√] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): Windows
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): 89.0.4389.90（正式版本） （64 位）
3. 扩展版本:  谷歌商店版 v2.0.9（版本异常）

### 重现步骤/尝试的解决方案
不清楚如何复现，但已经出现过多次。
具体表现为在使用一段时间后，会出现插件功能失效，查看设置界面会发现版本号从v2.0.9（publicBeta）变成v2.0.9（版本异常）
原本已经登录的账号会变成尚未登录，只能登录并提示注册（已经注册过了），再次注册会卡住（注册按钮变灰并卡住）
查看bilibilihelper.com，会始终显示“连接助手失败，点击刷新重试”
无法更改设置界面的任何选项，只能删除插件后在谷歌商店重新下载，版本号会变回v2.0.9（publicBeta）并一切正常。
额外信息：个人在两台计算机上都有该插件并使用同一账号，并都会不定期出现该问题，需要删除并重新下载。

**Comment by jjj201200** [comment]
后续版本会优化和修复各种问题，你可以加测试群提前试用最新测试版本

**Comment by jjj201200** [comment]
请更新至2.0.12版本。
