### ISSUE TITLE
评论区层主无法回复

### ISSUE THREAD

**Issue by wangxianzhuo** [bilibili-helper/bilibili-helper-o#834]
## 问题反馈
在您提交问题前, 请检查以下项目:
- [ ] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [ ] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): `Windows`
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): `Google Chrome 版本 89.0.4389.90（正式版本） （64 位）`
3. 扩展版本: `v2.0.9（publicBeta）`

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
启用扩展时在任意视频评论区任意层主点击`回复`没有任何反应
![image](https://user-images.githubusercontent.com/10629609/111937214-388ea500-8b02-11eb-9900-30f49d07cfca.png)
关闭扩展则恢复正常

**Comment by jjj201200** [comment]
尚未复现该问题，请排查是否只由助手导致该问题。排查时请关闭任何其他扩展或脚本程序

**Comment by wangxianzhuo** [comment]
我仔细测了一下，怀疑可能不是助手的问题，在没有任何插件的chrome上B站偶尔也会出现`回复`键没有反应，具体问题应该是在下图的这个click事件上。
在没有启动助手的时候，点击`回复`键有时会同时触发两次该事件，导致在第二次触发事件时，删除了第一次触发事件生成的回复框。
![image](https://user-images.githubusercontent.com/10629609/112279666-2312aa00-8cbf-11eb-80cb-8a297d630cd1.png)

**只能说我本地环境启动助手时，发生问题的情况比不启动助手的情况频率要高。**

**Comment by jjj201200** [comment]
向b站客服反馈吧
