### ISSUE TITLE
【特别关注】的模块是需要手动添加的吗，可以同步站内的特别关注么

### ISSUE THREAD

**Issue by CloudyEagle** [bilibili-helper/bilibili-helper-o#835]
1. 操作系统：Windows 10
2. 浏览器版本：Cent Browser Version 4.3.9.248 (Official Build) (64-bit) (Chromium 86.0.4240.198)
3. 扩展版本：2.0.11（publicBeta）
重现步骤
站内有【特别关注】的板块，是独立与站内的【特别关注】，还是可以同步而暂未实现呢？
![Snipaste_2021-03-24_17-39-05](https://user-images.githubusercontent.com/58777085/112292356-fa44e180-8ccb-11eb-9f5d-f0c764300af8.jpg)
![Snipaste_2021-03-24_18-08-22](https://user-images.githubusercontent.com/58777085/112292372-fdd86880-8ccb-11eb-9f16-9dbf6fe5e2c9.jpg)
这是我的看番小号，【特别关注】的是我的转载号（大号），已尝试重启浏览器排除。

**Comment by jjj201200** [comment]
暂时还不能同步b站的特关，助手的特关是服务于助手的功能的，和b站的无关

**Comment by CloudyEagle** [comment]
嗯，知道了。
