### ISSUE TITLE
目前直播版聊模式失效

### ISSUE THREAD

**Issue by yuijker** [bilibili-helper/bilibili-helper-o#837]
问题：
目前在网页全屏下，直播的控制栏直接与弹幕输入框重合，然后聊天框直接失去了顶部与右侧边框，而这正是用来调整聊天框大小和位置的地方。

不打开版聊模式与聊天框下

![屏幕截图 2021-04-13 183223](https://user-images.githubusercontent.com/72558803/114539259-e535ef80-9c86-11eb-88dd-c15330d61a68.png)

打开版聊模式与聊天框下

![屏幕截图 2021-04-13 183415](https://user-images.githubusercontent.com/72558803/114539276-e9faa380-9c86-11eb-9076-8f47f5f6fb47.png)

## 问题反馈
在您提交问题前, 请检查以下项目:
- [√ ] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [ √] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [√ ] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [ √] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):windows 10
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):Microsoft edge 89.0.774.76
3. 扩展版本:2.0.13

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)
1.打开扩展
2.进入一个直播间
3.开启版聊模式与聊天框
4.bug发生

**Comment by jjj201200** [comment]
该bug 已经在最新测试版本中修复，您可以前往http://d.bilibilihelper.com/下载并安装，注意测试版安装方法同正式版不同，具体见文档下方

**Comment by jjj201200** [comment]
谢谢你那么详细的说明问题情况。
除了SC按钮与全屏按钮重叠的问题我这边确实复现了之外
别的描述都没办法复现，请问你能在仅开启助手的情况下100%复现问题吗

**Comment by yuijker** [comment]
目前我发现，问题一、二、三与屏幕分辨率有关。
当屏幕分辨率为1920*1080甚至更高时，问题不会产生。
当屏幕分辨率为1920*1080以下时，问题将会很容易产生
我提供一个在1024*768下出现问题三的图

![屏幕截图 2021-04-15 194220](https://user-images.githubusercontent.com/72558803/114863778-c704f680-9e22-11eb-878d-8067f3915224.png)

**Comment by jjj201200** [comment]
好的好的，谢谢提供有价值的信息，我会排查调试一下是什么原因导致了这种问题

**Comment by yuijker** [comment]
从今天来看，持续多天的直播间的UI更新还造成一个bug，当直播分辨率接近网页全屏分辨率时，直播的一部分画面也被遮挡了，影响到观感。

![屏幕截图 2021-04-16 202429](https://user-images.githubusercontent.com/72558803/115023863-e880e380-9ef1-11eb-85b3-6d6c2758d2c8.png)

**Comment by yuijker** [comment]
目前在2.0.14版本下，在直播显示的横向分辨率低于正常的最大化窗口下就会产生这个议题所反馈的第二部分的问题一、二、三。目前该问题已在2.0.14.3下修复，但目前还有两个小bug。

一是，如果在分屏的情况下过度挤压直播分辨率时，聊天框会在接近其大小时开始整体闪烁起来。

![屏幕截图 2021-04-23 184801](https://user-images.githubusercontent.com/72558803/115860765-8e899c00-a464-11eb-8da9-60ffaeb57e74.png)

![屏幕截图 2021-04-23 184829](https://user-images.githubusercontent.com/72558803/115860772-90ebf600-a464-11eb-963f-b85c54cded57.png)

第二个是在分屏下，如果在版聊模式与正常的弹幕显示区里反复切换，将导致悬浮图标的移位，且重新将其移动向边缘将导致鼠标指针与悬浮图标远离，而且这一段移动距离是恒定的。

第一张图，启动版聊模式与聊天窗，移动图标至边缘

![屏幕截图 2021-04-23 185615](https://user-images.githubusercontent.com/72558803/115861915-060bfb00-a466-11eb-9518-82dcbb530562.png)

第二张图，点按图标时产生位移

![屏幕截图 2021-04-23 185644](https://user-images.githubusercontent.com/72558803/115861997-2340c980-a466-11eb-9037-704cc6afe24d.png)

第三张图，在版聊模式与正常的弹幕显示区里反复切换，导致图标也产生了位移

![屏幕截图 2021-04-23 185735](https://user-images.githubusercontent.com/72558803/115862110-48cdd300-a466-11eb-9161-1ac85e047676.png)

顺便说一下，在第三张图里的状态下，图标移动范围也变小了，无法放在边缘了。

**Comment by jjj201200** [comment]
悬浮球目前是有一些问题，这个问题是在悬浮球未上锁状态下才会产生的

**Comment by jjj201200** [comment]
已修复
