### ISSUE TITLE
[功能建议]直播分区屏蔽一些挂机直播间(自定义)

### ISSUE THREAD

**Issue by you-hengh** [bilibili-helper/bilibili-helper-o#839]
希望能添加直播分区屏蔽直播间的功能,使用场景
我的世界直播分区 80%都是挂机推广游戏服务器的直播间
找一个活人直播间真的千难万难
希望能提供屏蔽直播分区 直播间的功能 屏蔽这些挂机直播间
![image](https://user-images.githubusercontent.com/34816426/115303528-53eadf80-a196-11eb-9007-2ed5471b6735.png)

**Comment by jjj201200** [comment]
内容屏蔽功能不做哈
