### ISSUE TITLE
直播间聊天内容BUG

### ISSUE THREAD

**Issue by madmmmax** [bilibili-helper/bilibili-helper-o#842]
Chrome下未开启直播间屏蔽聊天内容，但是只有进入直播间的时候能看到有几条聊天内容，进入直播间以后新的聊天内容都看不见

**Comment by jjj201200** [comment]
请根据模板提交基础信息

**Comment by madmmmax** [comment]
> 请根据模板提交基础信息，目前没有复现该问题，请最小化系统浏览器的扩展以排查是助手造成的

感谢回复，我屏蔽其它插件再测试一下
