### ISSUE TITLE
直播间聊天内容BUG

### ISSUE THREAD

**Issue by madmmmax** [bilibili-helper/bilibili-helper-o#843]
**1. 操作系统:**
 Windows10 x64 20H2  19042.928
**2. 浏览器版本**
Edge  90.0.818.49
Chrome 64位 90.0.4430.93 
**3. 扩展版本:**
v2.0.16（publicBeta)

**### 重现步骤/尝试的解决方案**
进入直播间，右侧聊天框中会显示几条聊天信息，但是后续就没有任何变化，不会更新新的聊天内容

**备注：**
其实这个问题在我电脑上已经有一年了，老电脑是win10x64 ver.1902，由于我的chrome上插件很多，所以一直也没测试，今天换了新电脑，系统和插件都比较干净，还是有这个问题

**截图**
![Snipaste_2021-04-29_20-48-28](https://user-images.githubusercontent.com/64778400/116553541-d14be800-a92c-11eb-818e-8ee1c11ad95b.png)

![Snipaste_2021-04-29_20-49-23](https://user-images.githubusercontent.com/64778400/116553545-d315ab80-a92c-11eb-9d23-c7bfa21d7aed.png)

![Snipaste_2021-04-29_20-52-18](https://user-images.githubusercontent.com/64778400/116553549-d3ae4200-a92c-11eb-9d1f-80abc01c524c.png)

**Comment by jjj201200** [comment]
关闭助手之后就能显示了是吗

**Comment by madmmmax** [comment]
emmm...我测了下，助手关闭也不显示。这是为什么，手机上能显示。

**Comment by jjj201200** [comment]
这个时候呢，应该向b站官方客服反馈，对不
