### ISSUE TITLE
开启聊天框会导致视频硬件加速失效。

### ISSUE THREAD

**Issue by yuijker** [bilibili-helper/bilibili-helper-o#844]
请保留一种您需要的语言版本的报告模板
please leave only one kind of these template

## 问题反馈
在您提交问题前, 请检查以下项目:
- [x] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [x] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):Windows 10
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):Edge 90.0.818.51
3. 扩展版本:2.0.16.3

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)
开启聊天框时，从任务管理器上可以看到显卡的Video Processing没有利用率，3D利用率突然暴涨，CPU利用率也突然暴涨。
第一张图，没有打开聊天框时

![屏幕截图 2021-05-06 212120](https://user-images.githubusercontent.com/72558803/117305317-382f4b00-aeb1-11eb-92ad-acc9cab73c8f.png)

第二张图，打开聊天框时

![屏幕截图 2021-05-06 212224](https://user-images.githubusercontent.com/72558803/117305340-3f565900-aeb1-11eb-82d1-dcc0d7a3342e.png)

目前发现这一bug比较挑直播间，可能与up的直播流的设置也有关系。

**Comment by jjj201200** [comment]
可以给出一些能复现问题的信息吗，例如相关直播间
另外你有核显与独显，独显似乎没有启动

**Comment by yuijker** [comment]
目前来看，这个问题与直播间的流参数有关
我以一个从未来过的直播间举例
第一张，来到一个新直播间，未开启扩展的聊天框显示

![屏幕截图 2021-05-07 100913](https://user-images.githubusercontent.com/72558803/117388804-eec91500-af1d-11eb-9681-674dd48ba8e5.png)

第二张，聊天框显示打开，出现问题

![屏幕截图 2021-05-07 100948](https://user-images.githubusercontent.com/72558803/117388820-f4bef600-af1d-11eb-8676-13bf3510a218.png)

第三张，出现问题后立即关闭聊天框后

![屏幕截图 2021-05-07 101014](https://user-images.githubusercontent.com/72558803/117388834-f7b9e680-af1d-11eb-9d85-4ed67b81c3e0.png)

但是，我找到几个例外的直播间，如：22689676、2049028这些原画只有30FPS的就没有问题，大多数有问题的直播间的原画有60FPS的。
第一张，以22689676为例，未开启扩展的聊天框显示

![屏幕截图 2021-05-07 101856](https://user-images.githubusercontent.com/72558803/117388862-02747b80-af1e-11eb-9b31-039c89084fce.png)

第二张，聊天框显示打开，也没有出现问题

![屏幕截图 2021-05-07 101919](https://user-images.githubusercontent.com/72558803/117388874-07392f80-af1e-11eb-84d7-683f4b0f2a5b.png)

注：我个人怀疑可能我的硬件加速可能有限制，可能无法加速聊天框的渲染。

我的电脑的独显是MX110，是没有任何的视频硬件加速核心的，只能由核显来承担这份工作。

**Comment by jjj201200** [comment]
该issue先开着吧

**Comment by yuijker** [comment]
目前来看，随着edge90.0.818.66与2.1.0的扩展，我已经无法触发这个bug，这个问题已经解决了。

**Comment by jjj201200** [comment]
2.1.0已经调整了版聊模式的样式，之前的样式会导致css样式渲染上的性能问题
