### ISSUE TITLE
深色模式下视频简介为空（框选文字可以显示）

### ISSUE THREAD

**Issue by EndlessCheng** [bilibili-helper/bilibili-helper-o#845]
### 环境信息
1. 操作系统 (Windows/macOS/Linux): Win10
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): Edge 90.0.818.56
3. 扩展版本: 2.0.16

### 重现步骤/尝试的解决方案

任意视频均有

![111](https://user-images.githubusercontent.com/7086966/118345920-77713200-b56a-11eb-918f-6bcea42304f8.png)

**Comment by jjj201200** [comment]
已修复，请及时更新
