### ISSUE TITLE
视频下载功能与Xdown的下载增强插件有冲突

### ISSUE THREAD

**Issue by CloudyEagle** [bilibili-helper/bilibili-helper-o#847]
1. Operating System: Windows 10 20H2
2. Chrome Version: Center Browser - 百分浏览器
3. Extension Version: 2.1.2.5（版本异常）

Steps to Reproduce / Attempted solution
视频下载功能好像与Xdown的增强插件有冲突，会无法下载，
点击Xdown托管下载界面的“取消”也扔是无法下载；
关闭后才能正常下载。
![Snipaste_2021-06-02_15-17-02](https://user-images.githubusercontent.com/58777085/120699598-2c03d100-c4e3-11eb-9c10-147befb765ce.png)
![Snipaste_2021-06-02_16-03-56](https://user-images.githubusercontent.com/58777085/120699614-31611b80-c4e3-11eb-9266-233da35e75e2.png)

**Comment by jjj201200** [comment]
你应该去xdown那里反馈问题哈
