### ISSUE TITLE
`06-10` B站专栏样式已更新，黑暗模式失效，希望尽快适配新样式^拜托^

### ISSUE THREAD

**Issue by b4imetu** [bilibili-helper/bilibili-helper-o#851]
## 问题反馈
在您提交问题前, 请检查以下项目:
- [x] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): 21H1 19043.1052
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): Chrome 91
3. 扩展版本: 2.1.4

### 重现步骤/尝试的解决方案

- [x] `06-10` B站专栏样式已更新，黑暗模式失效，希望尽快适配新样式^拜托^
- [x] 另外2.1.4版本好像还没有解决大会员清晰度弹窗的问题

**Comment by jjj201200** [comment]
已经在下载文档发布2.1.4.1测试版，请前往[https://d.bilibilihelper.com/](https://d.bilibilihelper.com/)下载
